<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Airlines table seeder
    |--------------------------------------------------------------------------
    |
    | Lorem ipsum...
    |
    */

    'columns' => [
        'code',
        'title',
        'url',
        'phone',
        'is_major',
    ],

    'seeds' => [

        ['00', 'Anadolujet', null, null, 0],
        ['0A', 'Asta Linhas', null, null, 0],
        ['0B', 'Blue Air', 'https://www.flyblueair.com/en/gb/', '9091420598', 0],
        ['0C', 'Cobra Aviation', 'https://cobraaviation.co.za/', '27(0)11 395 14', 0],
        ['0D', 'Darwin Airline', null, null, 0],
        ['0J', 'Premium Jet', 'https://premiumjet.eu/', '41 44 307 50 8', 0],
        ['0V', 'VASCO', 'https://www.vietnamairlines.com/ca/en/Home', '778-379-2001', 0],
        ['0X', 'Copenhagen Express', null, null, 0],
        ['11', 'TUIfly (X3)', null, null, 0],
        ['12', '12 North', null, null, 0],
        ['1A', 'Amadeus Marketing S.A.', null, null, 0],
        ['1B', 'Abacus International', null, null, 0],
        ['1C', 'OneChina', null, null, 0],
        ['1D', 'Aerolinea de Antioquia', null, null, 0],
        ['1E', 'China Aviation Reservation', null, null, 0],
        ['1F', 'CB Airways UK ( Interliging Flights )', null, null, 0],
        ['1G', 'Galileo International', null, null, 0],
        ['1I', 'NetJets', null, null, 0],
        ['1J', 'Axess International Network', null, null, 0],
        ['1K', 'Southern Cross Distribution Systems', null, null, 0],
        ['1L', 'CitizenPlane', 'https://www.citizenplane.com/', null, 0],
        ['1N', 'Via World Network', null, null, 0],
        ['1P', 'Worldspan L.P.', null, null, 0],
        ['1R', 'Hainan Phoenix Info Sys', null, null, 0],
        ['1S', 'System One', null, null, 0],
        ['1T', 'Hitit Bilgisayar Hizmetleri', null, null, 0],
        ['1V', 'Galileo Intl Covia', null, null, 0],
        ['1W', 'Sabre', null, null, 0],
        ['1X', 'Branson Air Express', null, null, 0],
        ['1Z', 'Fantasia/asia Pacific Distribution.', null, null, 0],
        ['20', 'Air Salone', null, null, 0],
        ['24', 'Euro Jet', null, null, 0],
        ['2A', 'Deutsche Bahn', 'https://www.bahn.com/en', '49 30 31168290', 0],
        ['2B', 'AlbaWings', 'https://www.albawings.com/en/home', '355 (0)4580010', 0],
        ['2C', 'SNCF', null, null, 0],
        ['2D', 'Eastern Airlines', 'https://iflyea.com/', '855-216-7601', 0],
        ['2E', 'Smokey Bay Air', 'https://smokeybayair.com/index.html', '888-482-1511', 0],
        ['2F', 'Frontier Flying Service', null, '1-800-478-6779', 0],
        ['2G', 'Angara airlines', 'https://angara.aero/en/', '7 (3952) 287 9', 0],
        ['2H', 'Thalys', 'https://www.thalys.com/be/en', '32 70 66 77 88', 0],
        ['2I', 'Star Peru', 'https://www.starperu.com/es', '(01) 705-9000', 0],
        ['2J', 'Air Burkina', 'https://air-burkina.com/en', '226 25 49 23 4', 0],
        ['2K', 'Avianca Ecuador', 'https://www.avianca.com/ec/es/', '800-722-8222', 0],
        ['2L', 'Helvetic Airways', 'https://tabairlines.com/', '305-591-1965', 0],
        ['2M', 'Maya Island Air', 'https://www.mayaislandair.com/', '501-223-1403', 0],
        ['2N', 'NextJet', null, null, 0],
        ['2O', 'Island Air Kodiak', 'https://www.flyadq.com/', '907-487-4596', 0],
        ['2P', 'PAL Express', 'https://www.philippineairlines.com/en', '800-435-9725', 0],
        ['2Q', 'Air Cargo Carriers', 'https://www.aircargocarriers.com/', null, 0],
        ['2R', 'Atlantis European Airways', null, null, 0],
        ['2S', 'Air Stork', null, null, 0],
        ['2T', 'TruJet', 'https://www.trujet.com/#', '91 40 4090 409', 0],
        ['2U', 'Sun d’Or International Airlines', 'https://www.sundor.co.il/en/Pages/HomePage.aspx', '972-3-9771111', 0],
        ['2V', 'Amtrak', 'https://www.amtrak.com/home', '800-872-7245', 0],
        ['2W', 'World2fly', null, null, 0],
        ['2X', 'Airway Express,', 'http://www.airway.com.hk/', '852 23050832', 0],
        ['2Y', 'My Indo Airlines', 'https://www.myindoairlines.com/', '62 - 021 - 295', 0],
        ['2Z', 'Passaredo', 'https://www.voepass.com.br//empresa/site/', '0800 770 3757', 0],
        ['3A', 'Chu Kong Passenger Transport', 'https://cksp.com.hk/#/main/home', '852-2859 1669', 0],
        ['3B', 'Binter Cabo Verde', null, null, 0],
        ['3C', 'Air Chathams Limited', 'https://www.airchathams.co.nz/', '0800 580 127', 0],
        ['3D', 'Denim Air', null, null, 0],
        ['3E', 'Air Choice One', 'https://www.airchoiceone.com/', '866-435-9847', 0],
        ['3F', 'FLYONE ARMENIA', null, null, 0],
        ['3G', 'Atlant-Soyuz Airlines', null, null, 0],
        ['3H', 'Air Inuit', 'https://www.airinuit.com/en', '800-361-2965', 0],
        ['3I', 'Air Comet Chile', null, null, 0],
        ['3J', 'Jubba Airways', 'https://jubbaairways.com/', '254 20 2325573', 0],
        ['3K', 'Jetstar Asia Airways', 'https://www.jetstar.com/', '866-397-8170', 0],
        ['3L', 'Air Arabia Abu Dhabi', null, null, 0],
        ['3M', 'Silver Airways', 'https://www.silverairways.com/', '801-401-9100', 0],
        ['3N', 'Air Urga/air Urga', null, null, 0],
        ['3O', 'Air Arabia Maroc', 'https://www.airarabia.com/en/air-arabia-maroc', '080 2000 803', 0],
        ['3P', 'Tiara Air', null, null, 0],
        ['3Q', 'Yunnan Airlines', null, null, 0],
        ['3R', 'Divi Divi Air', null, null, 0],
        ['3S', 'Air Antilles Express', null, null, 0],
        ['3T', 'Turan Air', null, null, 0],
        ['3U', 'Sichuan Airlines', 'https://global.sichuanair.com/www/?country=CA-EN#/home', '86-28-8888-888', 0],
        ['3V', 'ASL Airlines Belgium', null, null, 0],
        ['3W', 'Malawian Airlines', null, null, 0],
        ['3X', 'Premier Trans Aire', null, null, 0],
        ['3Y', 'Baseops International', null, null, 0],
        ['3Z', 'Smartwings Poland', null, null, 0],
        ['47', '88', null, null, 0],
        ['4A', 'ATSA Airlines', null, null, 0],
        ['4B', 'BoutiqueAir', 'http://www.boutiqueair.com/', '855-268-8478', 0],
        ['4C', 'LATAM Colombia', null, '1 866 435-9526', 0],
        ['4D', 'Air Sinai', null, null, 0],
        ['4E', 'Stabo Air', null, null, 0],
        ['4F', 'Freedom Airline Express', null, null, 0],
        ['4G', 'Gazpromavia', null, null, 0],
        ['4H', 'HiSky', null, '1-800-241-6522', 0],
        ['4I', 'IZAir', null, null, 0],
        ['4J', 'Jetair Caribbean', null, null, 0],
        ['4K', 'Askari Aviation', null, null, 0],
        ['4L', 'Euroline', null, null, 0],
        ['4M', 'LATAM Argentina', 'https://www.latam.com/fr_fr/', '1 888 235 9826', 0],
        ['4N', 'Air North', null, null, 0],
        ['4O', 'Interjet', 'https://www.interjet.com', '1-844-874-4053', 0],
        ['4P', 'Regional sky', null, null, 0],
        ['4Q', 'Safi Airlines', null, null, 0],
        ['4R', 'Renfe', null, null, 0],
        ['4S', 'Solar Cargo', null, null, 0],
        ['4T', 'Rise Air', null, null, 0],
        ['4U', 'germanwings', 'https://www.eurowings.com/en.html', '1-845-709-8332', 0],
        ['4V', 'Fly Gangwon', null, null, 0],
        ['4W', 'Allied Air', null, null, 0],
        ['4X', 'Red Jet Mexico', null, null, 0],
        ['4Y', 'Eurowings Discover', null, null, 0],
        ['4Z', 'Airlink (SAA)', null, null, 0],
        ['5A', 'Alpine Air Express', null, null, 0],
        ['5B', 'Bassaka Air', null, null, 0],
        ['5C', 'Nature Air', null, '800-235-9272', 0],
        ['5D', 'Aerolitoral', null, '1-800-237-6639', 0],
        ['5E', 'SGA Airlines', null, null, 0],
        ['5F', 'FLY ONE', null, null, 0],
        ['5G', 'MAYAir', null, null, 0],
        ['5H', 'Fly540', null, null, 0],
        ['5J', 'Cebu Pacific', null, '632 7020888', 0],
        ['5K', 'Hi Fly', null, null, 0],
        ['5L', 'Aerosur', null, null, 0],
        ['5M', 'Sibaviatrans', null, null, 0],
        ['5N', 'Smartavia', null, null, 0],
        ['5O', 'ASL Airlines France', null, null, 0],
        ['5P', 'Small Planet Airlines', null, null, 0],
        ['5Q', 'Holiday Europe', null, null, 0],
        ['5R', 'Rutaca Airlines', null, null, 0],
        ['5S', 'S.A.P.', null, null, 0],
        ['5T', 'Canadian North', 'http://www.cdnair.ca/', '1-800-661-1505', 0],
        ['5U', 'Transportes Aéreos Guatemaltecos', null, null, 0],
        ['5V', 'Everts Air Cargo', null, null, 0],
        ['5W', 'Wizz Air Abu Dhabi', null, null, 0],
        ['5X', 'UPS', null, null, 0],
        ['5Y', 'Atlas Air', null, null, 0],
        ['5Z', 'Cem Air', null, null, 0],
        ['69', 'Royal European Airlines', null, null, 0],
        ['6A', 'Armenia Airways', null, null, 0],
        ['6B', 'TUI fly Nordic', null, '1-800-538-2583', 0],
        ['6C', 'Connect Linhas Aereas', null, null, 0],
        ['6D', 'Pelita Air', null, null, 0],
        ['6E', 'IndiGo Airlines', null, null, 1],
        ['6F', 'Primera Air Nordic', null, null, 0],
        ['6G', 'Air Wales', null, null, 0],
        ['6H', 'Israir', null, null, 0],
        ['6I', 'Alsie Express', null, null, 0],
        ['6J', 'Solaseed Air', null, null, 0],
        ['6K', 'Asian Spirit', null, null, 0],
        ['6L', 'Aklak', null, null, 0],
        ['6M', 'Maximus Air', null, null, 0],
        ['6N', 'Niger Airlines', null, null, 0],
        ['6O', 'Orbest', null, null, 0],
        ['6P', 'Gryphon Airlines', null, null, 0],
        ['6Q', 'Cham Wings Airlines', null, null, 0],
        ['6R', 'Alrosa', null, null, 0],
        ['6S', 'SaudiGulf Airlines', null, null, 0],
        ['6T', 'Air Mandalay', null, null, 0],
        ['6U', 'Air Cargo Germany', null, null, 0],
        ['6V', 'Lignes Aeriennes Congolaises', null, null, 0],
        ['6W', 'FlyBosnia', null, null, 0],
        ['6X', 'Amadeus Six', null, null, 0],
        ['6Y', 'SmartLynx Airlines', null, null, 0],
        ['6Z', 'Euro-Asia Air', null, null, 0],
        ['76', 'Southjet', null, null, 0],
        ['77', 'Southjet connect', null, null, 0],
        ['78', 'Southjet cargo', null, null, 0],
        ['7A', 'Express Air', null, null, 0],
        ['7B', 'Bees Airline', null, null, 0],
        ['7C', 'Jeju Air', null, null, 0],
        ['7D', 'Madagasikara Airways', null, null, 0],
        ['7E', 'Sylt Air', null, null, 0],
        ['7F', 'First Air', 'https://firstair.ca/', '800-267-1247', 0],
        ['7G', 'Star Flyer', null, null, 0],
        ['7H', 'Ravn Alaska', null, null, 0],
        ['7I', 'Insel Air', 'http://www.fly-inselair.com/', null, 0],
        ['7J', 'Tajik Air', null, null, 0],
        ['7K', 'Kogalymavia Air Company', null, null, 0],
        ['7L', 'Sun D’Or', null, null, 0],
        ['7M', 'MAP Linhas Aéreas', null, null, 0],
        ['7N', 'Pawa Dominicana', 'https://pawadominicana.com/en/', null, 0],
        ['7O', 'Smartwings Hungary Kft', null, null, 0],
        ['7P', 'AirPanama', null, null, 0],
        ['7Q', 'Elite Airways', null, null, 0],
        ['7R', 'Rusline', null, null, 0],
        ['7S', 'Ryan Air', null, null, 0],
        ['7T', 'Trenitalia', null, null, 0],
        ['7U', 'Commercial Aviation Services', null, null, 0],
        ['7V', 'Federal Airlines', null, null, 0],
        ['7W', 'Windrose Airlines', null, null, 0],
        ['7X', 'Amadeus Seven', null, null, 0],
        ['7Y', 'Mann Yadanarpon Airlines', null, null, 0],
        ['7Z', 'EZ Air', null, null, 0],
        ['8A', 'Atlas Blue', null, null, 0],
        ['8B', 'TransNusa', null, null, 0],
        ['8C', 'ATI', null, null, 0],
        ['8D', 'Astair', null, null, 0],
        ['8E', 'Bering Air', null, null, 0],
        ['8F', 'STP Airways', null, null, 0],
        ['8G', 'Mid Africa Aviation', null, null, 0],
        ['8H', 'Heli France', null, null, 0],
        ['8I', 'MyAir', null, '800-882-7822', 0],
        ['8J', 'Eco Jet', null, null, 0],
        ['8K', 'K-Mile Air', null, null, 0],
        ['8L', 'Lucky air', null, null, 0],
        ['8M', 'Myanmar Airways', null, null, 0],
        ['8N', 'Regional Air Services', null, null, 0],
        ['8O', 'West Coast Air', null, null, 0],
        ['8P', 'Pacific Coastal Airline', 'https://www.pacificcoastal.com/', '800-663-2872', 0],
        ['8Q', 'Onur Air', null, null, 0],
        ['8R', 'Sol Líneas Aéreas', null, null, 0],
        ['8S', 'Turbojet', null, null, 0],
        ['8T', 'Air Tindi', null, null, 0],
        ['8U', 'Afriqiyah Airways', null, null, 0],
        ['8V', 'Wright Air Service', null, null, 0],
        ['8W', 'Fly Allways', null, null, 0],
        ['8Y', 'Pan Pacific Airlines', null, null, 0],
        ['8Z', 'Wizz Air Hungary', null, null, 0],
        ['99', 'Ciao Air', null, null, 0],
        ['9A', 'GCA Airlines', null, null, 0],
        ['9B', 'AccesRail', null, null, 0],
        ['9C', 'Spring Airlines', null, null, 0],
        ['9D', 'Genghis Khan Airlines', null, null, 0],
        ['9E', 'Endeavor Air', null, null, 0],
        ['9F', 'Eurostar', null, null, 0],
        ['9G', '9G Rail', null, null, 0],
        ['9H', 'Air Changan', null, null, 0],
        ['9I', 'Alliance Air', null, null, 0],
        ['9J', 'Dana Airlines Limited', null, null, 0],
        ['9K', 'Cape Air', 'https://www.capeair.com/', '800-352-0714', 0],
        ['9L', 'Colgan Air', null, null, 0],
        ['9M', 'Central Mountain Air', 'https://www.flycma.com/', '888-865-8585', 0],
        ['9N', 'Tropic Air Limited', 'https://www.tropicair.com/', '501-226-2626', 0],
        ['9O', 'Transportes Aereos Inter', null, null, 0],
        ['9P', 'Air Arabia Jordan', null, null, 0],
        ['9Q', 'PB Air', null, null, 0],
        ['9R', 'SATENA', null, null, 0],
        ['9S', 'Southern Air', null, null, 0],
        ['9T', 'ACT Airlines', null, null, 0],
        ['9U', 'Air Moldova', null, null, 0],
        ['9V', 'Avior Airlines', 'http://www.aviorair.com', null, 0],
        ['9W', 'Jet Airways', 'https://www.jetairways.com/Information/home.html', '1-877-835-9538', 0],
        ['9X', 'Southern Airways Express', null, '18003290485', 0],
        ['9Y', 'Air Kazakhstan', null, null, 0],
        ['A0', 'Avianca Argentina', null, null, 0],
        ['A1', 'A.P.G. Distribution System', null, null, 0],
        ['A2', 'Animawings', null, null, 0],
        ['A3', 'Aegean', 'https://en.aegeanair.com/', '833-673-6110', 0],
        ['A4', 'Azimuth', null, null, 0],
        ['A5', 'HOP!', null, null, 0],
        ['A6', 'Air Travel', null, null, 0],
        ['A7', 'Calafia Airlines', null, null, 0],
        ['A8', 'Aerolink Uganda', null, null, 0],
        ['A9', 'Georgian Airways', null, null, 0],
        ['AA', 'American Airlines', 'https://www.aa.com/homePage.do', '800-433-7300', 1],
        ['AB', 'Air Berlin', 'https://www.airberlin.com', '1-866-266-5588', 0],
        ['AC', 'Air Canada', 'https://www.aircanada.com/ca/en/aco/home.html', '888-247-2262', 1],
        ['AD', 'Azul', 'https://www.voeazul.com.br/en/home', '888-587-2985', 0],
        ['AE', 'Mandarin Airlines', null, null, 0],
        ['AF', 'Air France', 'https://wwws.airfrance.ca/en', '800-667-2747', 1],
        ['AG', 'Aruba Airlines', 'http://www.arubaairlines.com/', null, 0],
        ['AH', 'Air Algerie', 'https://airalgerie.dz/en/', '213 21 98 63 6', 0],
        ['AI', 'Air India Limited', 'https://www.airindia.in/', '888-634-1407', 0],
        ['AJ', 'Aero Contractors', null, null, 0],
        ['AK', 'AirAsia', null, null, 0],
        ['AL', 'Malta Air', null, null, 0],
        ['AM', 'AeroMéxico', 'https://aeromexico.com/en-ca', '800 237- 6639', 0],
        ['AN', 'Advanced Air', null, null, 0],
        ['AO', 'Avianova (Russia)', null, null, 0],
        ['AP', 'AlbaStar', null, null, 0],
        ['AQ', '9 Air', null, null, 0],
        ['AR', 'Aerolineas Argentinas', 'https://www.aerolineas.com.ar/en-ar', '800-333-0276', 0],
        ['AS', 'Alaska Airlines', 'https://www.alaskaair.com/', '800-252-7522', 1],
        ['AT', 'Royal Air Maroc', 'https://www.royalairmaroc.com/ca-en', '800-344-6726', 0],
        ['AU', 'Canada Jetlines', null, null, 0],
        ['AV', 'Avianca', 'https://www.avianca.com/ca/en/', '800-722-8222', 0],
        ['AW', 'Africa World Airlines', 'https://www.flyafricaworld.com/', '800-200-200', 0],
        ['AX', 'Trans States Airlines', null, null, 0],
        ['AY', 'Finnair', 'https://www.finnair.com/ca-en', '647-946-9431', 0],
        ['AZ', 'ITA Airways', 'https://www.itaspa.com/en_en/', '866-725-7077', 0],
        ['B0', 'La Compagnie', null, '212 237 1790', 0],
        ['B1', 'Baltic Air lines', null, null, 0],
        ['B2', 'Belavia Belarusian Airlines', 'https://en.belavia.by/', null, 0],
        ['B3', 'Bhutan Airlines', null, null, 0],
        ['B4', 'ZanAir', null, null, 0],
        ['B5', 'East African', null, null, 0],
        ['B6', 'JetBlue Airways', 'https://www.jetblue.com/', '800-538-2583', 0],
        ['B7', 'Uni Air', null, null, 0],
        ['B8', 'Eritrean Airlines', null, null, 0],
        ['B9', 'Air Bangladesh', null, null, 0],
        ['BA', 'British Airways', 'https://www.britishairways.com/', '1800-247-9297', 1],
        ['BB', 'Seaborne Airlines', null, null, 0],
        ['BC', 'Skymark Airlines', null, null, 0],
        ['BD', 'Cambodia Bayon Airlines', null, null, 0],
        ['BE', 'flybe', null, '371 700 2000', 0],
        ['BF', 'French Bee', 'https://www.frenchbee.com/en', '833-376-7158', 0],
        ['BG', 'Biman Bangladesh Airlines', null, '880 2911 9995', 0],
        ['BH', 'Hawkair', null, null, 0],
        ['BI', 'Royal Brunei Airlines', null, null, 0],
        ['BJ', 'NouvelAir', null, null, 0],
        ['BK', 'Okay Airways', null, null, 0],
        ['BL', 'Jetstar Pacific', null, '61 3 9645 5999', 0],
        ['BM', 'flybmi', null, null, 0],
        ['BN', 'Luxwing', null, null, 0],
        ['BO', 'Bluebird Nordic', null, null, 0],
        ['BP', 'Air Botswana', null, '800-518-7781', 0],
        ['BQ', 'Buquebus Líneas Aéreas', null, null, 0],
        ['BR', 'EVA Air', 'https://www.evaair.com/en-us/index.html', '800-695-1188', 0],
        ['BS', 'US-Bangla Airlines', null, null, 0],
        ['BT', 'airBaltic', 'https://www.evaair.com/fr-fr/index.html', '800-548-8181', 0],
        ['BU', 'Compagnie Africaine d’Aviation CAA', null, null, 0],
        ['BV', 'Luke Air', null, null, 0],
        ['BW', 'Caribbean Airlines', 'https://www.caribbean-airlines.com/#/', '800-920-4225', 0],
        ['BX', 'Air Busan', null, null, 0],
        ['BY', 'TUI Airways', null, null, 0],
        ['BZ', 'Blue Bird Airways', null, null, 0],
        ['C0', 'Centralwings', null, null, 0],
        ['C1', 'CanXpress', null, null, 0],
        ['C2', 'Ceiba Intercontinental', null, null, 0],
        ['C3', 'Trade Air', null, null, 0],
        ['C4', 'LionXpress', null, null, 0],
        ['C5', 'CommutAir', null, null, 0],
        ['C6', 'Canjet Airlines', null, '800-809-7777', 0],
        ['C7', 'Cinnamon Air', null, null, 0],
        ['C8', 'Cronos Airlines', null, null, 0],
        ['C9', 'SkyWise', null, null, 0],
        ['CA', 'Air China', 'https://www.airchina.ca/', '800-882-8122', 1],
        ['CB', 'CCML Airlines', null, null, 0],
        ['CC', 'CM Airlines', null, null, 0],
        ['CD', 'Corendon Dutch Airlines B.V.', null, null, 0],
        ['CE', 'Chalair', null, null, 0],
        ['CF', 'City Airline', null, null, 0],
        ['CG', 'PNG Air', null, '675 325 2011', 0],
        ['CH', 'Bemidji Airlines', null, '800-332-7133', 0],
        ['CI', 'China Airlines', 'https://www.china-airlines.com/us/en', '800-227-5118', 0],
        ['CJ', 'BA CityFlyer', null, null, 0],
        ['CK', 'China Cargo', null, null, 0],
        ['CL', 'Lufthansa CityLine', null, null, 0],
        ['CM', 'Copa Airlines', 'https://www.copaair.com/en/web/ca', '647-493-5022', 0],
        ['CN', 'Grand China Air', null, null, 0],
        ['CO', 'Cobalt Air', null, '1-800-523-3273', 0],
        ['CP', 'Compass Airlines', null, null, 0],
        ['CQ', 'Coastal Aviation', null, null, 0],
        ['CS', 'Continental Micronesia', null, null, 0],
        ['CT', 'Alitalia Cityliner', null, '1-800-223-5730', 0],
        ['CU', 'Cubana de Aviación', 'http://www.cubana.cu/', null, 0],
        ['CV', 'Cargolux', null, '1-800-866-2885', 0],
        ['CW', 'Air Marshall Islands', null, '1-692-625-3733', 0],
        ['CX', 'Cathay Pacific', 'https://www.cathaypacific.com/cx/en_CA.html', '833-895-3535', 0],
        ['CY', 'Cyprus Airways', 'https://www.flyniki.com/fr/start.php', null, 0],
        ['CZ', 'China Southern Airlines', 'https://www.csair.com/ca/en/index.shtml', '86 4008695539-', 1],
        ['D0', 'DHL Air', null, null, 0],
        ['D1', 'Domenican Airlines', null, null, 0],
        ['D2', 'Severstal Air Company', null, null, 0],
        ['D3', 'Daallo Airlines', null, null, 0],
        ['D4', 'Aerodart', null, null, 0],
        ['D5', 'DHL Aero Expreso', null, null, 0],
        ['D6', 'Interair South Africa', null, null, 0],
        ['D7', 'AirAsia X', null, null, 0],
        ['D8', 'Norwegian International', null, '1-800-357-4159', 0],
        ['D9', 'Aeroflot-Don', null, null, 0],
        ['DA', 'Aerolinea de Antioquia', null, null, 0],
        ['DB', 'Brit Air', null, null, 0],
        ['DC', 'Braathens Regional Airways', null, null, 0],
        ['DD', 'Nok Air', null, null, 0],
        ['DE', 'Condor', 'https://www.condor.com/us', '866-960-7915', 0],
        ['DF', 'Michael Airlines', null, null, 0],
        ['DG', 'CebGo', null, null, 0],
        ['DH', 'Dennis Sky', null, null, 0],
        ['DI', 'Norwegian Air UK', null, '1-800-357-4159', 0],
        ['DJ', 'AirAsia Japan', null, null, 0],
        ['DK', 'Sunclass Airlines', null, null, 0],
        ['DL', 'Delta Air Lines', 'https://www.delta.com/ca/en', '800-221-1212', 1],
        ['DM', 'Arajet', null, null, 0],
        ['DN', 'Norwegian Air Argentina', null, null, 0],
        ['DO', 'Dominicana de Aviaci', null, null, 0],
        ['DP', 'Pobeda', null, null, 0],
        ['DQ', 'Coastal Air', null, null, 0],
        ['DR', 'Ruili Airlines', null, null, 0],
        ['DS', 'EasyJet (DS)', null, '44330 3655454', 0],
        ['DT', 'TAAG Angola Airlines', 'http://www.taag.com/', null, 0],
        ['DU', 'Air Liaison', null, null, 0],
        ['DV', 'Scat Airlines', null, null, 0],
        ['DW', 'Great Dane Airlines', null, null, 0],
        ['DX', 'DAT Danish Air Transport', null, null, 0],
        ['DY', 'Norwegian', 'https://www.norwegian.com/us/', '47 2149 00 15', 0],
        ['DZ', 'Donghai Airlines', null, null, 0],
        ['E0', 'Eos', null, null, 0],
        ['E1', 'Usa Sky Cargo', null, null, 0],
        ['E2', 'Eurowings Europe', null, '44 330 365 191', 0],
        ['E3', 'EGO Airways', null, null, 0],
        ['E4', 'Enter Air', null, null, 0],
        ['E5', 'Air Arabia Egypt', null, null, 0],
        ['E6', 'Bringer Air Cargo Taxi', null, null, 0],
        ['E7', 'Equaflight Services', null, null, 0],
        ['E8', 'Tayaranjet', null, null, 0],
        ['E9', 'Iberojet Airlines', null, null, 0],
        ['EA', 'Emerald Airlines', null, null, 0],
        ['EB', 'Wamos Air', null, null, 0],
        ['EC', 'Easyjet Europe', null, '44330 3655454', 0],
        ['ED', 'AirExplore', null, null, 0],
        ['EE', 'RegionalJet', null, null, 0],
        ['EF', 'EF', null, null, 0],
        ['EG', 'Ernest Airlines', null, null, 0],
        ['EH', 'ANA Wings', null, null, 0],
        ['EI', 'Aer Lingus', 'https://www.aerlingus.com/html/en-CA/home.html', '800-474-7424', 0],
        ['EJ', 'New England Airlines', null, '800-243-2460', 0],
        ['EK', 'Emirates', 'https://www.emirates.com/ca/english/', '800-777-3999', 1],
        ['EL', 'Ellinair', null, null, 0],
        ['EM', 'Empire Airlines', null, null, 0],
        ['EN', 'Air Dolomiti', null, null, 0],
        ['EO', 'Pegas Fly', null, null, 0],
        ['EP', 'Iran Aseman Airlines', null, null, 0],
        ['EQ', 'TAME', 'https://www.tame.com.ec/index.php/en/', '1800 430 2471', 0],
        ['ER', 'SereneAir', null, null, 0],
        ['ES', 'Estelar Latinoamerica', null, null, 0],
        ['ET', 'Ethiopian Airlines', 'https://www.ethiopianairlines.com/aa/en', '613-701-6473', 0],
        ['EU', 'Chengdu Airlines', null, null, 0],
        ['EV', 'aha!', null, null, 0],
        ['EW', 'Eurowings', 'https://www.eurowings.com/en.html', '833-272-1446', 0],
        ['EX', 'Regional Express Americas', null, null, 0],
        ['EY', 'Etihad Airways', 'https://www.etihad.com/en-ca/', '866-948-1081', 0],
        ['EZ', 'Sun Air of Scandinavia', null, null, 0],
        ['F0', 'Fly Jordan', null, null, 0],
        ['F1', 'Fly Brasil', null, null, 0],
        ['F2', 'Safarilink Aviation', null, null, 0],
        ['F3', 'Flyadeal', null, null, 0],
        ['F4', 'Air Flamenco', null, null, 0],
        ['F5', 'Aerotranscargo', null, null, 0],
        ['F6', 'FlyValan', null, null, 0],
        ['F7', 'iFly Airlines', null, null, 0],
        ['F8', 'Flair Airlines', 'https://flyflair.com/', '833-711-2333', 0],
        ['F9', 'Frontier Airlines', 'https://www.flyfrontier.com/', '801-401-9000', 0],
        ['FA', 'Fly Safair', null, null, 0],
        ['FB', 'Bulgaria Air', 'https://www.air.bg/en', '359 2 402 04 0', 0],
        ['FC', 'Link Airways', 'https://www.linkairways.com/', '61 2 6123 1999', 0],
        ['FD', 'Thai AirAsia', null, null, 0],
        ['FE', '748 Air Services', null, null, 0],
        ['FF', 'Tower Air', null, null, 0],
        ['FG', 'Ariana Afghan Airlines', null, null, 0],
        ['FH', 'Freebird Airlines', null, null, 0],
        ['FI', 'Icelandair', 'https://www.icelandair.com/en-ca/', '800-223-5500', 0],
        ['FJ', 'Fiji Airways', 'https://www.fijiairways.com/en-ca/', '800-227-4446', 0],
        ['FK', 'Africa West', null, null, 0],
        ['FL', 'Air Leap', 'https://www.southwest.com/', '1-800-247-8726', 0],
        ['FM', 'Shanghai Airlines', 'https://fr.ceair.com/fr/', null, 0],
        ['FN', 'Fastjet', null, null, 0],
        ['FO', 'Flybondi', null, null, 0],
        ['FP', 'Pelican Airlines', null, null, 0],
        ['FQ', 'Thomas Cook Airlines', null, null, 0],
        ['FR', 'Ryanair', 'https://www.ryanair.com/us/en', '44 1279358438', 1],
        ['FS', 'Flyr', null, null, 0],
        ['FT', 'FlyEgypt FT', null, null, 0],
        ['FU', 'Fuzhou Airlines', null, null, 0],
        ['FV', 'Rossiya-Russian Airlines', null, '812 333-22-22', 0],
        ['FW', 'Ibex Airlines', null, null, 0],
        ['FX', 'Fedex Airlines', null, null, 0],
        ['FY', 'Firefly', null, null, 0],
        ['FZ', 'Fly Dubai', 'https://www.flydubai.com', null, 0],
        ['G0', 'Ghana International Airlines', null, null, 0],
        ['G1', 'Indya Airline Group', null, null, 0],
        ['G2', 'GullivAir', null, null, 0],
        ['G3', 'Gol Transportes Aéreos', 'https://www.voegol.com.br/en', '855-862-9190', 0],
        ['G4', 'Allegiant Air', 'https://www.allegiantair.com/', '702-505-8888', 0],
        ['G5', 'China Express Airlines', null, null, 0],
        ['G6', 'Air Volga', null, null, 0],
        ['G7', 'GoJet Airlines', null, null, 0],
        ['G8', 'Go Air', null, null, 0],
        ['G9', 'Air Arabia', null, null, 0],
        ['GA', 'Garuda Indonesia', 'https://www.garuda-indonesia.com/other-countries/en/index', '08041-807-807', 0],
        ['GB', 'BRAZIL AIR', null, null, 0],
        ['GC', 'Global Feeder Services', null, null, 0],
        ['GD', 'Aviar PTY LTD', null, null, 0],
        ['GE', 'LIFT airline', null, null, 0],
        ['GF', 'Gulf Air Bahrain', 'https://www.gulfair.com/', '855-359-4853', 0],
        ['GG', 'Air Guyane', null, null, 0],
        ['GH', 'Globus', null, null, 0],
        ['GI', 'Itek Air', null, null, 0],
        ['GJ', 'Loong Air', null, null, 0],
        ['GK', 'Jetstar Japan', null, '61 3 9645 5999', 0],
        ['GL', 'Air Greenland', null, '299 34 34 34', 0],
        ['GM', 'Chair Airlines', null, null, 0],
        ['GN', 'GNB Linhas Aereas', null, null, 0],
        ['GO', 'ULS Airlines Cargo', null, null, 0],
        ['GP', 'APG Airlines', 'https://www.apg-airlines.com/search?lang=en_US', null, 0],
        ['GQ', 'Sky Express', null, '0030 215 215 6', 0],
        ['GR', 'Aurigny Air Services', null, null, 0],
        ['GS', 'Tianjin Airlines', null, null, 0],
        ['GT', 'Air Guilin', null, null, 0],
        ['GU', 'Avianca Guatemala', null, null, 0],
        ['GV', 'Grant Aviation', null, null, 0],
        ['GW', 'Costa Rica Green Airways', null, null, 0],
        ['GX', 'GX airlines', null, null, 0],
        ['GY', 'Colorful Guizhou Airlines', null, null, 0],
        ['GZ', 'Air Rarotonga', null, null, 0],
        ['H1', 'Hahn Air', 'https://www.hahnair.com/', null, 0],
        ['H2', 'Sky Airline', null, null, 0],
        ['H3', 'Thomas Cook Aviation', null, null, 0],
        ['H4', 'HiSky Europe', null, null, 0],
        ['H5', 'I-Fly', null, '1 855 7593665', 0],
        ['H6', 'Bulgarian Air Charter', null, '1-866-239-0119', 0],
        ['H7', 'HiSky', null, null, 0],
        ['H8', 'Sky Airline Peru', null, null, 0],
        ['H9', 'Himalaya Airlines', null, null, 0],
        ['HA', 'Hawaiian Airlines', 'https://www.hawaiianairlines.com/', '800-367-5320', 1],
        ['HB', 'Homer Air', null, null, 0],
        ['HC', 'Air Senegal', 'https://flyairsenegal.com/en/home/', '877-411-9134', 0],
        ['HD', 'Air Do', null, null, 0],
        ['HE', 'Luftfahrtgesellschaft Walter', null, null, 0],
        ['HF', 'Air Cote d’Ivoire', null, '22921315823', 0],
        ['HG', 'Hibernian Airlines', 'https://www.flyniki.com/en/start.php', null, 0],
        ['HH', 'Taban Airlines', null, null, 0],
        ['HI', 'Papillon Grand Canyon Helicopters', null, null, 0],
        ['HJ', 'Tasman Cargo Airlines', null, null, 0],
        ['HK', 'Yangon Airways', null, null, 0],
        ['HM', 'Air Seychelles', null, null, 0],
        ['HN', 'Equair', null, null, 0],
        ['HO', 'Juneyao Airlines', null, null, 0],
        ['HP', 'Amapola Flyg', null, null, 0],
        ['HQ', 'Thomas Cook Belgium', null, null, 0],
        ['HR', 'Hahn Airlines', 'https://www.hahnair.com/en', '855-HAHNAIR (4', 0],
        ['HS', 'Heli Securite', null, null, 0],
        ['HT', 'Air Horizont', null, null, 0],
        ['HU', 'Hainan Airlines', 'https://www.hainanairlines.com/CA/GB/Home', '888-688-8813', 0],
        ['HV', 'Transavia', 'https://www.transavia.com/en-EU/home/', '31 20 4060406', 0],
        ['HW', 'Hello', null, null, 0],
        ['HX', 'Hong Kong Airlines', 'https://www.hongkongairlines.com/en_CA/homepage', '1-855-393-3880', 0],
        ['HY', 'Uzbekistan Airways', null, '371 67324563', 0],
        ['HZ', 'Aurora Airlines', null, null, 0],
        ['I0', 'LEVEL operated by Iberia', null, null, 0],
        ['I2', 'Iberia Express', null, '1-800-772-4642', 0],
        ['I3', 'ATA Airlines (Iran)', null, null, 0],
        ['I4', 'Island Air Express', null, null, 0],
        ['I5', 'AirAsia India', null, null, 0],
        ['I6', 'Air indus', null, null, 0],
        ['I7', 'Int’Air Iles', null, null, 0],
        ['I8', 'Izhavia', null, null, 0],
        ['I9', 'Air Italy', null, '1 800 746-1888', 0],
        ['IA', 'Iraqi Airways', null, null, 0],
        ['IB', 'Iberia Airlines', 'https://www.iberiaexpress.com/en', '0034 919 046 3', 0],
        ['IC', 'Indian Airlines', null, null, 0],
        ['ID', 'Batik Air', null, null, 0],
        ['IE', 'Solomon Airlines', null, '800-677-4277', 0],
        ['IF', 'Fly Baghdad Airlines', null, null, 0],
        ['IG', 'Air Italy', 'https://www.airitaly.com/fr-fr/', '1 800 746-1888', 0],
        ['IH', 'Southern Sky', null, null, 0],
        ['II', 'IBC Airways', null, null, 0],
        ['IJ', 'Spring Airlines Japan', null, null, 0],
        ['IK', 'Air Kiribati', null, null, 0],
        ['IL', 'Trigana Air', null, null, 0],
        ['IM', 'Jupiter Jet', null, null, 0],
        ['IN', 'Nam Air', null, null, 0],
        ['IO', 'IrAero', null, null, 0],
        ['IP', 'Island Spirit', null, null, 0],
        ['IQ', 'Qazaq Air', null, null, 0],
        ['IR', 'Iran Air', null, null, 0],
        ['IS', 'Fly Ais Airlines', null, '800-323-3345', 0],
        ['IT', 'Tigerair Taiwan', null, null, 0],
        ['IU', 'Super Air Jet', null, null, 0],
        ['IV', 'GP Aviation', null, null, 0],
        ['IW', 'Wings Air', null, null, 0],
        ['IX', 'Air India Express', null, '800-223-7776', 0],
        ['IY', 'Yemenia', null, null, 0],
        ['IZ', 'Arkia', null, null, 0],
        ['J0', 'Jam Air Link Express Limited', null, null, 0],
        ['J1', 'One Jet', null, null, 0],
        ['J2', 'Azerbaijan Airlines', 'https://www.azal.az/en/', '994 (12) 598-8', 0],
        ['J3', 'Northwestern Air', null, null, 0],
        ['J4', 'Badr Airlines', null, null, 0],
        ['J5', 'Alaska Seaplane Service', null, null, 0],
        ['J6', 'Jet Ops', null, null, 0],
        ['J7', 'Afrijet Business Service', null, null, 0],
        ['J8', 'Berjaya Air', null, null, 0],
        ['J9', 'Jazeera Airways', null, null, 0],
        ['JA', 'JetSMART', null, null, 0],
        ['JB', 'Helijet', null, null, 0],
        ['JC', 'JAL Express', null, null, 0],
        ['JD', 'Beijing Capital Airlines', null, '86-95071999', 0],
        ['JE', 'Mango', null, null, 0],
        ['JF', 'Jetairfly', null, null, 0],
        ['JG', 'JetGo', null, null, 0],
        ['JH', 'Fuji Dream Airlines', null, null, 0],
        ['JI', 'Meraj Air', null, '800-446-4392', 0],
        ['JJ', 'LATAM Brasil', 'https://www.latam.com', '1 888 235 9826', 0],
        ['JK', 'Spanair', null, null, 0],
        ['JL', 'Japan Airlines', 'https://www.jal.co.jp/ar/en/?city=YVR', '1-800-525-3663', 1],
        ['JM', 'Jambojet', null, null, 0],
        ['JN', 'JOON', null, null, 0],
        ['JO', 'Jonika airlines', null, null, 0],
        ['JP', 'Adria Airways', 'https://www.adria.si/fr/', null, 0],
        ['JQ', 'Jetstar Airways', 'https://www.jetstar.com/', '866-397-8170', 0],
        ['JR', 'Joy Air', null, '1-800-AERO CAL', 0],
        ['JS', 'Air Koryo', null, null, 0],
        ['JT', 'Lion Air', null, null, 0],
        ['JU', 'Air Serbia', 'http://www.jetupaviation.com/', '833-538-7249', 0],
        ['JV', 'Perimeter Aviation', null, null, 0],
        ['JW', 'Vanilla Air', null, null, 0],
        ['JX', 'Starlux Airlines', null, null, 0],
        ['JY', 'interCaribbean Airways', 'https://www.intercaribbean.com/', '888-957-3223', 0],
        ['JZ', 'JetSMART Peru', null, null, 0],
        ['K1', 'Kostromskie avialinii', null, null, 0],
        ['K2', 'EuroLot', null, null, 0],
        ['K3', 'Safe Air Company', null, null, 0],
        ['K4', 'Kalitta Air', null, null, 0],
        ['K5', 'Silverstone Air', null, null, 0],
        ['K6', 'Cambodia Angkor Air', null, null, 0],
        ['K7', 'Air KBZ', null, null, 0],
        ['K8', 'Kan Air', null, null, 0],
        ['K9', 'KrasAvia (old iata)', null, null, 0],
        ['KA', 'Cathay Dragon', 'https://www.cathaypacific.com/cx/fr_FR.html', null, 0],
        ['KB', 'Druk Air', null, null, 0],
        ['KC', 'Air Astana', null, null, 0],
        ['KD', 'Kalstar Aviation', null, null, 0],
        ['KE', 'Korean Air', 'https://www.koreanair.com/ca/en', '800-438-5000', 0],
        ['KF', 'Air Belgium', null, null, 0],
        ['KG', 'Key Lime Air', null, null, 0],
        ['KH', 'Aloha Air Cargo', null, '800-367-5250', 0],
        ['KI', 'SKS Airways', null, null, 0],
        ['KJ', 'British Mediterranean Airways', null, null, 0],
        ['KK', 'AtlasGlobal', null, null, 0],
        ['KL', 'KLM Royal Dutch Airlines', 'https://www.klm.ca/', '800-375-8723', 0],
        ['KM', 'Air Malta', null, '800-756-2582', 0],
        ['KN', 'China United', null, null, 0],
        ['KO', 'Komiaviatrans', null, null, 0],
        ['KP', 'ASKY Airlines', 'https://www.flyasky.com/tg/en/', '228 22 23 05 0', 0],
        ['KQ', 'Kenya Airways', 'https://www.kenya-airways.com/ca/en/', '855-967-4428', 0],
        ['KR', 'Cambodia Airways', null, null, 0],
        ['KS', 'Peninsula Airways', 'http://www.penair.com/', '800-448-4226', 0],
        ['KT', 'VickJet', null, null, 0],
        ['KU', 'Kuwait Airways', 'https://www.kuwaitairways.com/en', '201-582-9200', 0],
        ['KV', 'Kavminvodyavia', null, null, 0],
        ['KW', 'Carnival Air Lines', null, null, 0],
        ['KX', 'Cayman Airways', 'https://www.caymanairways.com/', '800-422-9626', 0],
        ['KY', 'Kunming Airlines', null, null, 0],
        ['KZ', 'NCA - Nippon Cargo Airlines', null, null, 0],
        ['L0', 'Reliant Air', null, null, 0],
        ['L2', 'Lynden Air Cargo', null, null, 0],
        ['L3', 'LTU Austria', null, null, 0],
        ['L4', 'LASA Argentina', null, null, 0],
        ['L5', 'Atlas Atlantique Airlines', null, null, 0],
        ['L6', 'Mauritania Airlines International', null, null, 0],
        ['L7', 'Lugansk Airlines', null, null, 0],
        ['L8', 'Line Blue', null, null, 0],
        ['L9', 'Lumiwings', null, null, 0],
        ['LA', 'LATAM Airlines', 'https://www.latamairlines.com/ca/en', '888-235-9826', 0],
        ['LB', 'Air Costa', null, null, 0],
        ['LC', 'Skyway CR', null, null, 0],
        ['LD', 'AHK', null, null, 0],
        ['LE', 'Norwegian Air Sweden LE', null, null, 0],
        ['LF', 'Contour Airlines', null, '1 888 332-6686', 0],
        ['LG', 'Luxair', null, '352 2456 4242', 0],
        ['LH', 'Lufthansa', 'https://www.lufthansa.com/ca/en/homepage', '833-951-2503', 1],
        ['LI', 'Leeward Islands Air Transport', 'http://www.liat.com/', null, 0],
        ['LJ', 'Jin Air', null, null, 0],
        ['LK', 'Lao Skyway', null, null, 0],
        ['LL', 'China General Aviation', null, null, 0],
        ['LM', 'LoganAir LM', null, null, 0],
        ['LN', 'Libyan Arab Airlines', null, null, 0],
        ['LO', 'LOT Polish Airlines', 'https://www.lot.com/ca/en', '416-236-4242', 0],
        ['LP', 'LATAM Peru', null, '1 888 235 9826', 0],
        ['LQ', 'Lanmei Airlines', null, null, 0],
        ['LR', 'Avianca Costa Rica', 'https://www.avianca.com/ca/en/', '800-722-8222', 0],
        ['LS', 'Jet2', null, null, 0],
        ['LT', 'LongJiang Airlines', null, null, 0],
        ['LU', 'LATAM Express', null, '1 888 235 9826', 0],
        ['LV', 'Level', null, null, 0],
        ['LW', 'Latin American Wings', null, null, 0],
        ['LX', 'Swiss International Air Lines', 'https://www.swiss.com/ca/en/homepage', '833-951-2504', 0],
        ['LY', 'El Al Israel Airlines', 'https://www.elal.com/en/Canada/Pages/default.aspx', '97239771111', 0],
        ['LZ', 'belleair', null, null, 0],
        ['M0', 'Aero Mongolia', null, null, 0],
        ['M1', 'Maryland Air', null, null, 0],
        ['M2', 'Rhein-Neckar Air', null, null, 0],
        ['M3', 'Air Norway', null, null, 0],
        ['M4', 'Mistral Air', null, null, 0],
        ['M5', 'Kenmore Air', null, null, 0],
        ['M6', 'Amerijet International', null, null, 0],
        ['M7', 'MasAir', null, null, 0],
        ['M8', 'SkyJet Airlines', null, null, 0],
        ['M9', 'Motor Sich', null, null, 0],
        ['MA', 'Malév', null, null, 0],
        ['MB', 'MNG Airlines', null, null, 0],
        ['MC', 'Air Mobility Command', null, null, 0],
        ['MD', 'Air Madagascar', null, '800-821-3388', 0],
        ['ME', 'Middle East Airlines', 'https://www.mea.com.lb/', '514-954-1464', 0],
        ['MF', 'Xiamen Airlines', 'https://www.xiamenair.com/en-ca/', '855-789-5557', 0],
        ['MG', 'Eznis Airways', null, null, 0],
        ['MH', 'Malaysia Airlines', 'https://www.malaysiaairlines.com/hq/en.html', '603 7843 3000', 0],
        ['MI', 'SilkAir', 'https://www.singaporeair.com/en_UK/us/home#/book/bookflight', null, 0],
        ['MJ', 'Myway Airlines', null, null, 0],
        ['MK', 'Air Mauritius', 'http://www.airmauritius.com/index_re.htm', '800-537-1182', 0],
        ['ML', 'Air Mediterranee', null, null, 0],
        ['MM', 'Peach Aviation', null, null, 0],
        ['MN', 'Kulula', null, '800-354-9822', 0],
        ['MO', 'Calm Air', null, null, 0],
        ['MP', 'Martinair', null, '800-627-8462', 0],
        ['MQ', 'Envoy Air as American Eagle', null, null, 0],
        ['MR', 'Hunnu Air', null, null, 0],
        ['MS', 'Egyptair', 'https://www.egyptair.com/en/Pages/default.aspx', '001 (416) 960-', 0],
        ['MT', 'Malta MedAir', null, '1 855 7593665', 0],
        ['MU', 'China Eastern Airlines', 'https://ca.ceair.com/en/', '416-926-8998', 1],
        ['MV', 'Air Mediterranean', null, null, 0],
        ['MW', 'Mokulele Flight Service', 'http://www.mokuleleairlines.com/', '1-808-495-4188', 0],
        ['MX', 'Breeze Airways', 'https://www.flybreeze.com/home', '501-273-3931', 0],
        ['MY', 'MASwings', null, null, 0],
        ['MZ', 'Merpati Nusantara Airlines', null, null, 0],
        ['N0', 'Norse Atlantic Airways', 'https://flynorse.com', null, 0],
        ['N1', 'N1', null, null, 0],
        ['N2', 'Jet Charter', null, null, 0],
        ['N3', 'Vuela El Salvador', null, null, 0],
        ['N4', 'Nordwind Airlines', null, null, 0],
        ['N5', 'Skagway Air Service', 'https://owg.com/en/', null, 0],
        ['N6', 'Nomad Aviation', null, null, 0],
        ['N7', 'Nordic Regional Airlines', 'http://www.neptuneair.com/', null, 0],
        ['N8', 'National Airlines', null, null, 0],
        ['N9', 'Novair', null, null, 0],
        ['NA', 'Nesma Air', null, null, 0],
        ['NB', 'Sterling Airlines', null, null, 0],
        ['NC', 'National Jet Systems', null, null, 0],
        ['ND', 'FMI Air', null, null, 0],
        ['NE', 'Nesma Air', null, null, 0],
        ['NF', 'Air Vanuatu', null, '800-677-4277', 0],
        ['NG', 'Lauda Air', null, null, 0],
        ['NH', 'All Nippon Airways', 'https://www.ana.co.jp/en/ca/', '844-728-0647', 1],
        ['NI', 'Portugalia', null, null, 0],
        ['NJ', 'Nordic Global Airlines', null, null, 0],
        ['NK', 'Spirit Airlines', 'https://www.spirit.com/', '855-728-3555', 0],
        ['NL', 'Amelia', null, null, 0],
        ['NM', 'Air Madrid', null, null, 0],
        ['NN', 'VIM Airlines', null, null, 0],
        ['NO', 'Neos Air', null, null, 0],
        ['NP', 'Nile Air', null, null, 0],
        ['NQ', 'Air Japan', null, null, 0],
        ['NR', 'Manta Air', null, null, 0],
        ['NS', 'Hebei Airlines', null, null, 0],
        ['NT', 'Binter Canarias', null, '902 391 392', 0],
        ['NU', 'Japan Transocean Air', null, null, 0],
        ['NV', 'Nakanihon Airlines', null, null, 0],
        ['NW', 'Northwest Airlines', null, '800-225-2525', 0],
        ['NX', 'Air Macau', null, null, 0],
        ['NY', 'Air Iceland Connect', null, null, 0],
        ['NZ', 'Air New Zealand', 'https://www.airnewzealand.ca/', '866‑351‑9528', 1],
        ['O1', 'Orbit Airlines Azerbaijan', null, null, 0],
        ['O2', 'Linear Air', null, null, 0],
        ['O3', 'Orange Air', null, null, 0],
        ['O4', 'Orange2Fly', null, null, 0],
        ['O5', 'Comores Aviation', null, null, 0],
        ['O6', 'Avianca Brazil', null, null, 0],
        ['O7', 'Orenburzhye Airline', null, null, 0],
        ['O8', 'Siam Air', null, null, 0],
        ['O9', 'NOVA Airways', null, null, 0],
        ['OA', 'Olympic Air', 'https://www.olympicair.com/en', '1-800-223-1226', 0],
        ['OB', 'Boliviana de Aviación', 'https://www.boa.bo/BoAWebSite/', '800-584-4099', 0],
        ['OC', 'Oriental Air Bridge', null, null, 0],
        ['OD', 'Malindo Air', null, null, 0],
        ['OE', 'LaudaMotion', null, null, 0],
        ['OF', 'Overland Airways', null, null, 0],
        ['OG', 'Play', null, null, 0],
        ['OH', 'Comair', null, null, 0],
        ['OI', 'Hinterland Aviation', null, null, 0],
        ['OJ', 'NyxAir', null, null, 0],
        ['OK', 'Czech Airlines', 'https://www.csa.cz/ca-fr/', '1-855-359-2932', 0],
        ['OL', 'Samoa Airways', null, null, 0],
        ['OM', 'MIAT Mongolian Airlines', null, null, 0],
        ['ON', 'Nauru Air Corporation', null, null, 0],
        ['OO', 'SkyWest', null, null, 0],
        ['OP', 'PassionAir', null, null, 0],
        ['OQ', 'Chongqing Airlines', null, null, 0],
        ['OR', 'TUI fly Netherlands', null, null, 0],
        ['OS', 'Austrian Airlines', 'https://www.austrian.com/ca/en/homepage', '800-843 0002', 0],
        ['OT', 'Aeropelican Air Services', null, null, 0],
        ['OU', 'Croatia Airlines', 'http://www.croatiaairlines.com/', '888-462-7628', 0],
        ['OV', 'SalamAir', null, '800-397-1354', 0],
        ['OW', 'Skyward Express Limited', null, null, 0],
        ['OX', 'Canarian Airways', null, null, 0],
        ['OY', 'Andes Líneas Aéreas', null, null, 0],
        ['OZ', 'Asiana Airlines', 'https://flyasiana.com/', '800-227-4262', 0],
        ['P0', 'Proflight Zambia', null, null, 0],
        ['P1', 'Regional Sky', null, null, 0],
        ['P2', 'Air Kenya', null, null, 0],
        ['P3', 'Cargologicair', null, null, 0],
        ['P4', 'Air Peace Limited', null, null, 0],
        ['P5', 'Wingo airlines', null, '1 800 359 2672', 0],
        ['P6', 'Pascan Aviation', null, null, 0],
        ['P7', 'Small Planet Airline', null, null, 0],
        ['P8', 'Sprint Air', null, null, 0],
        ['P9', 'Peruvian Airlines', null, null, 0],
        ['PA', 'Airblue', null, null, 0],
        ['PB', 'PAL Airlines', 'https://www.palairlines.ca/en/', '800-563-2800', 0],
        ['PC', 'Pegasus', 'https://www.flypgs.com/fr', '011 90 850 250', 0],
        ['PD', 'Porter Airlines', 'https://www.flyporter.com/en-ca/', '888-619-8622', 0],
        ['PE', 'People’s Viennaline PE', null, null, 0],
        ['PF', 'Primera Air', null, null, 0],
        ['PG', 'Bangkok Airways', 'https://www.bangkokair.com/eng/', '866-226-4565', 0],
        ['PH', 'Polynesian Airlines', null, null, 0],
        ['PI', 'Polar Airlines', null, null, 0],
        ['PJ', 'Air Saint Pierre', null, null, 0],
        ['PK', 'Pakistan International Airlines', null, '1-800-221-2552', 0],
        ['PL', 'Southern Air Charter', null, null, 0],
        ['PM', 'Canary Fly', null, null, 0],
        ['PN', 'West Air China', null, null, 0],
        ['PO', 'Polar Airlines', null, null, 0],
        ['PP', 'Air Indus', null, null, 0],
        ['PQ', 'SkyUp Airlines', null, null, 0],
        ['PR', 'Philippine Airlines', 'https://www.philippineairlines.com/en', '800-435-9725', 0],
        ['PS', 'Ukraine International Airlines', 'https://www.flyuia.com/fr/fr/home', '1 8008760114', 0],
        ['PT', 'Red Jet Andes', null, null, 0],
        ['PU', 'Plus Ultra Lineas Aereas', null, null, 0],
        ['PV', 'St Barth Commuter', null, null, 0],
        ['PW', 'Precision Air', null, null, 0],
        ['PX', 'Air Niugini', null, null, 0],
        ['PY', 'Surinam Airways', null, '305 599 1196', 0],
        ['PZ', 'LATAM Paraguay', null, '1 888 235 9826', 0],
        ['Q2', 'Maldivian', null, null, 0],
        ['Q3', 'Anguilla Air Services', null, null, 0],
        ['Q4', 'Euroairlines', null, null, 0],
        ['Q5', '40-Mile Air', null, null, 0],
        ['Q6', 'Volaris Costa Rica', null, '1-800-122-8000', 0],
        ['Q7', 'Sky Bahamas', null, null, 0],
        ['Q8', 'Trans Air Congo', null, null, 0],
        ['Q9', 'Green Africa Airways', null, null, 0],
        ['QA', 'Click (Mexicana)', null, null, 0],
        ['QB', 'Qeshm Air', null, null, 0],
        ['QC', 'Camair-co', null, null, 0],
        ['QD', 'JC International Airlines', null, null, 0],
        ['QE', 'Express Freighters Australia', null, null, 0],
        ['QF', 'Qantas', 'https://www.qantas.com/ca/en.html', '800-227-4500', 1],
        ['QG', 'Citilink', null, null, 0],
        ['QH', 'Bamboo Airways', null, null, 0],
        ['QI', 'Ibom Air', null, null, 0],
        ['QJ', 'Jet Airways', null, null, 0],
        ['QK', 'Air Canada Jazz', null, '1-888-247-2262', 0],
        ['QL', 'Laser Air', null, null, 0],
        ['QM', 'Monacair', null, null, 0],
        ['QN', 'Skytrans', null, null, 0],
        ['QO', 'Origin Pacific Airways', null, null, 0],
        ['QP', 'Starlight Airline', null, null, 0],
        ['QQ', 'Alliance Airlines', null, null, 0],
        ['QR', 'Qatar Airways', 'https://www.qatarairways.com/', '877-777-2827', 1],
        ['QS', 'Smartwings', null, null, 0],
        ['QT', 'Avianca Cargo', null, null, 0],
        ['QU', 'Azur Air Ukraine', null, null, 0],
        ['QV', 'Lao Airlines', 'http://www.laoairlines.com/', null, 0],
        ['QW', 'Qingdao Airlines', null, null, 0],
        ['QX', 'Horizon Air', null, '800-547-9308', 0],
        ['QY', 'Red Jet Canada', null, null, 0],
        ['QZ', 'Indonesia AirAsia', null, null, 0],
        ['R0', 'Tantalus Air', null, null, 0],
        ['R2', 'Orenburg Airlines', null, null, 0],
        ['R3', 'Yakutia Airlines', null, null, 0],
        ['R4', 'Real Tonga', null, null, 0],
        ['R5', 'Jordan Aviation', null, null, 0],
        ['R6', 'DAT LT', null, null, 0],
        ['R7', 'Aserca Airlines', null, null, 0],
        ['R8', 'AirRussia', null, null, 0],
        ['R9', 'Suasa Airlines', null, null, 0],
        ['RA', 'Nepal Airlines', null, '800-266-3725', 0],
        ['RB', 'Syrian Arab Airlines', null, null, 0],
        ['RC', 'Atlantic Airways', null, null, 0],
        ['RD', 'Ryan International Airlines', null, null, 0],
        ['RE', 'Stobart Air', null, null, 0],
        ['RF', 'Florida West International Airways', null, null, 0],
        ['RG', 'Rotana Jet', null, null, 0],
        ['RH', 'Republic Express Airlines', null, null, 0],
        ['RI', 'Mandala Airlines', null, null, 0],
        ['RJ', 'Royal Jordanian', 'https://www.rj.com/en/', '962.6.5100000', 0],
        ['RK', 'Ryanair UK', null, null, 0],
        ['RL', 'Royal Flight Airlines', null, null, 0],
        ['RM', 'Armenia Aircompany', null, null, 0],
        ['RN', 'Rayani Air', null, null, 0],
        ['RO', 'Tarom', 'http://www.tarom.ro/fr/', '973 884 3254', 0],
        ['RP', 'Chautauqua Airlines', null, null, 0],
        ['RQ', 'Kam Air', null, null, 0],
        ['RR', 'Buzz', null, '44 8715005050', 0],
        ['RS', 'Air Seoul', null, null, 0],
        ['RT', 'JSC UVT Aero', null, null, 0],
        ['RU', 'AirBridgeCargo', null, null, 0],
        ['RV', 'Air Canada Rouge', null, '1-888-247-2262', 0],
        ['RW', 'Royal Air Philippines', null, null, 0],
        ['RX', 'Regent Airways', null, null, 0],
        ['RY', 'Air Jiangxi', null, null, 0],
        ['RZ', 'Sansa Air', null, null, 0],
        ['S0', 'Aerolineas Sosa', null, null, 0],
        ['S1', 'Serbian Airlines', null, null, 0],
        ['S2', 'Jet Konnect', null, null, 0],
        ['S3', 'SBA Airlines', 'http://www.sbairlines.com/', null, 0],
        ['S4', 'SATA Azores Airlines', 'https://www.azoresairlines.pt/en', '(+351) 296 209', 0],
        ['S5', 'Shuttle America', null, null, 0],
        ['S6', 'Sunrise Airways', null, null, 0],
        ['S7', 'S7 Airlines', 'https://www.s7.ru/', '1-800-772-4642', 0],
        ['S8', 'Sounds Air', null, null, 0],
        ['S9', 'Starbow Airlines', null, null, 0],
        ['SA', 'South African Airways', 'https://www.flysaa.com/', '902-612-2438', 0],
        ['SB', 'Aircalin', null, null, 0],
        ['SC', 'Shandong Airlines', null, '0531-96777', 0],
        ['SD', 'Sudan Airways', null, null, 0],
        ['SE', 'XL Airways France', 'http://www.xl.com/', '1-877-496-9889', 0],
        ['SF', 'Tassili Airlines', null, null, 0],
        ['SG', 'Spicejet', null, null, 0],
        ['SH', 'Sharp Airlines', null, null, 0],
        ['SI', 'Blue Islands', null, null, 0],
        ['SJ', 'Sriwijaya Air', null, null, 0],
        ['SK', 'SAS', 'https://www.flysas.com/en/', '855-593-6279', 0],
        ['SL', 'Thai Lion Air', null, null, 0],
        ['SM', 'Air Cairo', null, null, 0],
        ['SN', 'Brussels Airlines', 'https://www.brusselsairlines.com/', '32 2 723 23 62', 0],
        ['SO', 'Salsa dHaiti', null, null, 0],
        ['SP', 'SATA Air Acores', null, null, 0],
        ['SQ', 'Singapore Airlines', 'https://www.singaporeair.com/', '416-945-0299', 1],
        ['SR', 'Sundair', null, null, 0],
        ['SS', 'Corsair International', 'https://www.corsair.fr/', '1 888-222-4346', 0],
        ['ST', 'Germania', 'https://www.airthanlwin.com/', '(+95-1) 400365', 0],
        ['SU', 'Aeroflot Russian Airlines', 'https://www.aeroflot.ru/xx-en', '866-221-7291', 0],
        ['SV', 'Saudia', 'https://www.saudia.com/?sc_lang=en-CA&sc_country=CA', '855-588-0999', 0],
        ['SW', 'Air Namibia', null, '800-626-4242', 0],
        ['SX', 'SkyWork Airlines', null, null, 0],
        ['SY', 'Sun Country Airlines', 'https://www.suncountry.com/', '651-905-2737', 0],
        ['SZ', 'Somon Air', null, null, 0],
        ['T0', 'Avianca Peru', null, null, 0],
        ['T2', 'Thai Air Cargo', null, null, 0],
        ['T3', 'Eastern Airways', null, null, 0],
        ['T4', 'Hellas Jet', null, null, 0],
        ['T5', 'Turkmenistan Airlines', null, null, 0],
        ['T6', 'Airswift', null, null, 0],
        ['T7', 'Twin Jet', null, null, 0],
        ['T8', 'Terra Avia', null, null, 0],
        ['T9', 'Turpial Airlines', null, null, 0],
        ['TA', 'Avianca El Salvador', 'https://www.avianca.com/ca/en/', '800-284-2622', 0],
        ['TB', 'TUI fly Belgium', null, null, 0],
        ['TC', 'Air Tanzania', null, null, 0],
        ['TD', 'Atlantis European Airways', null, null, 0],
        ['TE', 'FlyLal', null, null, 0],
        ['TF', 'Braathens Regional Aviation', null, null, 0],
        ['TG', 'Thai Airways International', 'https://www.thaiairways.com/', '800-767-3598', 0],
        ['TH', 'Raya Airways', null, null, 0],
        ['TI', 'Tailwind Airlines', null, null, 0],
        ['TJ', 'Tradewind Aviation', null, null, 0],
        ['TK', 'Turkish Airlines', 'https://www.turkishairlines.com/en-ca/', '800-874-8875', 1],
        ['TL', 'Airnorth', null, null, 0],
        ['TM', 'LAM Mozambique Airlines', null, null, 0],
        ['TN', 'Air Tahiti Nui', 'https://www.airtahitinui.com/us-en', '877-824-4846', 0],
        ['TO', 'Transavia France', null, null, 0],
        ['TP', 'TAP Portugal', 'https://www.flytap.com/en-ca/', '800-903-7914', 0],
        ['TQ', 'Tandem Aero', null, null, 0],
        ['TR', 'Scoot', null, null, 0],
        ['TS', 'Air Transat', 'https://www.airtransat.com/', '877-872-6728', 0],
        ['TT', 'Tiger Airways Australia', null, '61 7 3295 2104', 0],
        ['TU', 'Tunisair', 'http://www.tunisair.com/site/publish/content/', '514 819 0495', 0],
        ['TV', 'Tibet Airlines', null, null, 0],
        ['TW', 'Tway Airlines', null, null, 0],
        ['TX', 'Air Caraïbes', null, '877.772-1005', 0],
        ['TY', 'Air Caledonie', null, null, 0],
        ['TZ', 'Tsaradia', null, null, 0],
        ['U1', 'Aviabus', null, null, 0],
        ['U2', 'easyJet', 'https://www.easyjet.com/us', '44 (0) 330 551', 0],
        ['U3', 'Avies', null, null, 0],
        ['U4', 'Buddha Air', null, null, 0],
        ['U5', 'United Nigeria', null, null, 0],
        ['U6', 'Ural Airlines', null, null, 0],
        ['U7', 'Northern Dene Airways', null, null, 0],
        ['U8', 'TUS Airways', null, null, 0],
        ['U9', 'Tatarstan Airlines', null, null, 0],
        ['UA', 'United Airlines', 'https://www.united.com/en/ca/', '800-864-8331', 1],
        ['UB', 'Myanmar National Airlines', null, null, 0],
        ['UC', 'LATAM Cargo Chile', null, null, 0],
        ['UD', 'UR Airlines', null, null, 0],
        ['UE', 'Nasair', null, null, 0],
        ['UF', 'UM Airlines', null, null, 0],
        ['UG', 'TunisAir Express', null, null, 0],
        ['UH', 'AtlasGlobal Ukraine', null, null, 0],
        ['UI', 'Auric Air', null, null, 0],
        ['UJ', 'AlMasria Universal Airlines', null, null, 0],
        ['UK', 'Air Vistara', null, null, 0],
        ['UL', 'SriLankan Airlines', 'https://www.srilankan.com/en_uk/ca', '416-227-9000', 0],
        ['UM', 'Air Zimbabwe', null, '800-742-3006', 0],
        ['UN', 'Transaero Airlines', null, null, 0],
        ['UO', 'Hong Kong Express Airways', null, null, 0],
        ['UP', 'Bahamasair', 'https://www.bahamasair.com/', '800-222-4262', 0],
        ['UQ', 'Urumqi Airlines', null, null, 0],
        ['UR', 'Uganda Airlines', null, null, 0],
        ['US', 'US Airways', 'https://www.aa.com', '1-800-943-5436', 0],
        ['UT', 'UTair', null, null, 0],
        ['UU', 'Air Austral', null, null, 0],
        ['UV', 'Universal Airways', null, null, 0],
        ['UW', 'Uni-Top Airlines', null, null, 0],
        ['UX', 'Air Europa', 'https://www.aireuropa.com/us/en/home', '844-415-3955', 0],
        ['UY', 'Sky Prime Charter', null, null, 0],
        ['UZ', 'El-Buraq Air Transport', null, null, 0],
        ['V0', 'Conviasa', null, null, 0],
        ['V2', 'Vision Airlines', null, null, 0],
        ['V3', 'Carpatair', null, null, 0],
        ['V4', 'Vieques Air Link', null, null, 0],
        ['V5', 'Aerovías DAP', null, null, 0],
        ['V6', 'VIP Ecuador', null, null, 0],
        ['V7', 'Volotea', null, '011 34 931 22', 0],
        ['V8', 'ATRAN Cargo Airlines', null, null, 0],
        ['V9', 'Star1 Airlines', null, null, 0],
        ['VA', 'Virgin Australia Airlines', 'https://www.virginaustralia.com/us/en/#/', '855-253-8021', 0],
        ['VB', 'VivaAerobus', 'https://web.vivaaerobus.com/en', '866-359-8482', 0],
        ['VC', 'Via Air', null, null, 0],
        ['VD', 'Air Libert', null, null, 0],
        ['VE', 'VE', null, null, 0],
        ['VF', 'Valuair', null, null, 0],
        ['VG', 'VLM Airlines', null, null, 0],
        ['VH', 'Viva Air', 'https://www.vivaair.com/co/en', '855-652-0600', 0],
        ['VI', 'Volga-Dnepr Airlines', null, null, 0],
        ['VJ', 'VietJet Air', null, null, 0],
        ['VK', 'LEVEL EUROPE', null, null, 0],
        ['VL', 'Med-View Airline', null, null, 0],
        ['VM', 'Max Air', null, null, 0],
        ['VN', 'Vietnam Airlines', 'https://www.vietnamairlines.com/ca/en/Home', '778 379 2001', 0],
        ['VO', 'Voyage Air', null, null, 0],
        ['VP', 'Villa Air', null, null, 0],
        ['VQ', 'Novoair', null, null, 0],
        ['VR', 'Cabo Verde Airlines', null, null, 0],
        ['VS', 'Virgin Atlantic Airways', 'https://www.virginatlantic.com/', '800-862-8621', 0],
        ['VT', 'Air Tahiti', null, null, 0],
        ['VU', 'Vietravel Airlines', null, null, 0],
        ['VV', 'Viva Air', 'https://www.vivaair.com/us/en', '855-652-0600', 0],
        ['VW', 'Aeromar', 'https://www.aeromar.mx/en/home/', '844 237-6629', 0],
        ['VX', 'Virgin America', 'https://www.virginamerica.com/', null, 0],
        ['VY', 'Vueling', 'http://www.vueling.com/en', '34931518158', 0],
        ['VZ', 'Thai Vietjet', null, null, 0],
        ['W1', 'World Experience Airline', null, null, 0],
        ['W2', 'Flexflight', null, null, 0],
        ['W3', 'Arik Air', 'http://www.arikair.com', null, 0],
        ['W4', 'Ulendo Airlink', null, null, 0],
        ['W5', 'Mahan Air', null, null, 0],
        ['W6', 'Wizz Air', null, null, 0],
        ['W7', 'Wings of Lebanon', null, null, 0],
        ['W8', 'Cargojet Airways', null, null, 0],
        ['W9', 'Wizz Air UK', null, null, 0],
        ['WA', 'KLM Cityhopper', null, null, 0],
        ['WB', 'Rwandair Express', 'http://rwandair.com', '44 01293 874 9', 0],
        ['WC', 'Avianca Honduras', null, null, 0],
        ['WD', 'Amsterdam Airlines', null, null, 0],
        ['WE', 'Thai Smile', null, null, 0],
        ['WF', 'Widerøe', null, '47 81001200', 0],
        ['WG', 'Sunwing', 'https://www.sunwing.ca/en/', '877-786-9464', 0],
        ['WH', 'WDL Aviation', null, null, 0],
        ['WI', 'White Airways', null, null, 0],
        ['WJ', 'JetSMART Argentina', null, '1.800.563.3042', 0],
        ['WK', 'Edelweiss Air', null, null, 0],
        ['WL', 'World Atlantic Airlines', null, null, 0],
        ['WM', 'Windward Islands Airways', null, '(866) 466-0410', 0],
        ['WN', 'Southwest Airline', 'https://www.southwest.com/', '800-435-9792', 1],
        ['WO', 'Swoop', 'https://www.flyswoop.com/', '587-441-1001', 0],
        ['WP', 'Air Antwerp', 'https://www.islandair.com/', null, 0],
        ['WQ', 'Swiftair', null, null, 0],
        ['WR', 'WestJet Encore', null, '1-888-937-8538', 0],
        ['WS', 'WestJet', 'https://www.westjet.com/en-ca', '888-937-8538', 0],
        ['WT', 'SwiftAir', null, null, 0],
        ['WU', 'Jetways Airlines Limited', null, null, 0],
        ['WV', 'Westair Aviation', null, '800-626-4242', 0],
        ['WW', 'WOW air', 'https://fr.wowair.ca/', null, 0],
        ['WX', 'CityJet', null, null, 0],
        ['WY', 'Oman Air', 'https://www.omanair.com/ca/en', '437-888-3160', 0],
        ['WZ', 'Red Wings', null, null, 0],
        ['X1', 'Hahn Air Technologies', 'https://www.hahnair.com', '49 6103 7331', 0],
        ['X2', 'China Xinhua', null, null, 0],
        ['X3', 'TUI fly Deutschland', null, '0180 6000 120', 0],
        ['X4', 'Air Excursions', null, null, 0],
        ['X5', 'Air Europa express', null, null, 0],
        ['X7', 'Challenge Airlines', null, null, 0],
        ['X8', 'Airmax', null, null, 0],
        ['X9', 'Avion Express', null, null, 0],
        ['XA', 'ARINC', null, null, 0],
        ['XB', 'NEXT Brasil', null, null, 0],
        ['XC', 'Corendon', null, null, 0],
        ['XD', 'Airlines Reporting Crp', null, null, 0],
        ['XE', 'JetSuiteX', null, null, 0],
        ['XF', 'Vladivostok Air', null, null, 0],
        ['XG', 'SunExpress', null, null, 0],
        ['XJ', 'Thai AirAsia X', null, null, 0],
        ['XK', 'Air Corsica', null, null, 0],
        ['XL', 'LATAM Ecuador', 'https://www.latamairlines.com/ca/en', '888-235-9826', 0],
        ['XM', 'Alitalia Express', null, null, 0],
        ['XN', 'Xpressair', null, null, 0],
        ['XO', 'LTE International Airways', null, null, 0],
        ['XP', 'Avelo', 'https://www.aveloair.com/', '346-616-9500', 0],
        ['XQ', 'SunExpress', null, null, 0],
        ['XR', 'Corendon Airlines Europe', null, null, 0],
        ['XT', 'Indonesia AirAsia X', null, null, 0],
        ['XU', 'African Express', null, null, 0],
        ['XV', 'BVI Airways', null, null, 0],
        ['XW', 'NokScoot', null, null, 0],
        ['XX', 'Greenfly', null, null, 0],
        ['XY', 'flynas', null, null, 0],
        ['XZ', 'Congo Express', null, '1-800-722-9675', 0],
        ['Y0', 'Yellow Airtaxi', null, null, 0],
        ['Y1', 'Yellowstone Club Private Shuttle', null, null, 0],
        ['Y2', 'AirCentury', null, null, 0],
        ['Y3', 'Sky Kg', null, null, 0],
        ['Y4', 'Volaris', 'https://www.volaris.com/', '855-8652747', 0],
        ['Y5', 'Golden Myanmar Airlines', null, null, 0],
        ['Y6', 'AB Aviation', null, null, 0],
        ['Y7', 'NordStar Airlines', null, null, 0],
        ['Y8', 'Suparna Airlines', null, null, 0],
        ['Y9', 'Lynx', 'http://flylynx.com/', null, 0],
        ['YB', 'Harbour Air (Priv)', null, null, 0],
        ['YC', 'Yamal Air', null, null, 0],
        ['YD', 'Gomelavia', null, null, 0],
        ['YE', 'Yan Air', null, null, 0],
        ['YG', 'YTO Cargo', null, null, 0],
        ['YH', 'Air Thanlwin', null, null, 0],
        ['YI', 'Yunnan Ying’An Airlines', null, null, 0],
        ['YJ', 'Asian Wings Air', null, null, 0],
        ['YK', 'Avia Traffic Airline', null, null, 0],
        ['YL', 'Libyan Wings', null, null, 0],
        ['YM', 'Montenegro Airlines', null, null, 0],
        ['YN', 'Air Creebec', 'https://www.aircreebec.ca/', '800-567-6567', 0],
        ['YO', 'TransHolding System', null, null, 0],
        ['YP', 'Air Premia', null, null, 0],
        ['YQ', 'TAR Aerolineas', null, null, 0],
        ['YR', 'SENIC AIRLINES', null, null, 0],
        ['YS', 'Régional', null, null, 0],
        ['YT', 'Yeti Airways', null, null, 0],
        ['YU', 'EuroAtlantic Airways', null, null, 0],
        ['YV', 'Mesa Airlines', null, '800-637-2247', 0],
        ['YW', 'Air Nostrum', null, null, 0],
        ['YX', 'Republic Airlines', null, null, 0],
        ['YY', 'Virginwings', null, null, 0],
        ['YZ', 'Alas Uruguay', null, null, 0],
        ['Z0', 'Norse Atlantic UK', 'https://flynorse.com', null, 0],
        ['Z2', 'Philippines AirAsia', null, null, 0],
        ['Z3', 'Avient Aviation', null, null, 0],
        ['Z4', 'Ibom Air', null, null, 0],
        ['Z5', 'Global Africa Aviation', null, null, 0],
        ['Z6', 'Dniproavia', null, null, 0],
        ['Z7', 'Amaszonas Uruguay', null, null, 0],
        ['Z8', 'Amaszonas', null, null, 0],
        ['Z9', 'Bek Air', null, null, 0],
        ['ZA', 'Sky Angkor Airlines', null, null, 0],
        ['ZB', 'Air Albania', null, null, 0],
        ['ZC', 'Korongo Airlines', null, null, 0],
        ['ZD', 'EWA Air', null, null, 0],
        ['ZE', 'Eastar Jet', null, null, 0],
        ['ZF', 'Azur Air', null, null, 0],
        ['ZG', 'ZIPAIR', null, null, 0],
        ['ZH', 'Shenzhen Airlines', 'http://global.shenzhenair.com/zh/main.jsp', '1-647-525-5820', 0],
        ['ZI', 'Aigle Azur', null, null, 0],
        ['ZJ', 'Zambezi Airlines (ZMA)', null, null, 0],
        ['ZK', 'Great Lakes Airlines', null, '1-800-554-5111', 0],
        ['ZL', 'Regional Express', null, null, 0],
        ['ZM', 'Air Manas', null, null, 0],
        ['ZN', 'Zenith International Airline', null, null, 0],
        ['ZO', 'Zagros Airlines', null, null, 0],
        ['ZP', 'Paranair', null, null, 0],
        ['ZQ', 'German Airways', null, null, 0],
        ['ZR', 'Aviacon Zitotrans', null, null, 0],
        ['ZS', 'Sama Airlines', null, null, 0],
        ['ZT', 'Titan Airways', null, null, 0],
        ['ZU', 'Ethiopian Mozambique Airlines', null, null, 0],
        ['ZV', 'V Air', null, null, 0],
        ['ZW', 'Air Wisconsin', null, null, 0],
        ['ZX', 'Japan Regio', null, null, 0],
        ['ZY', 'Ada Air', null, null, 0],
        ['ZZ', 'Zz', null, null, 0],

    ],

];
