DROP TABLE IF EXISTS countries;

CREATE TABLE countries (
    code char(2) NOT NULL DEFAULT '',
    code_iso_3 char(3) NOT NULL DEFAULT '',
    title varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO countries (code, code_iso_3, title)
VALUES
	('AD', 'AND', 'Andorra'),
    ('AE', 'ARE', 'United Arab Emirates'),
    ('AF', 'AFG', 'Afghanistan'),
    ('AG', 'ATG', 'Antigua and Barbuda'),
    ('AI', 'AIA', 'Anguilla'),
    ('AL', 'ALB', 'Albania'),
    ('AM', 'ARM', 'Armenia'),
    ('AN', 'ANT', 'Netherlands Antilles'),
    ('AO', 'AGO', 'Angola'),
    ('AQ', 'ATA', 'Antarctica'),
    ('AR', 'ARG', 'Argentina'),
    ('AS', 'ASM', 'American Samoa'),
    ('AT', 'AUT', 'Austria'),
    ('AU', 'AUS', 'Australia'),
    ('AW', 'ABW', 'Aruba'),
    ('AX', 'ALA', 'Aland Islands'),
    ('AZ', 'AZE', 'Azerbaijan'),
    ('BA', 'BIH', 'Bosnia and Herzegovina'),
    ('BB', 'BRB', 'Barbados'),
    ('BD', 'BGD', 'Bangladesh'),
    ('BE', 'BEL', 'Belgium'),
    ('BF', 'BFA', 'Burkina Faso'),
    ('BG', 'BGR', 'Bulgaria'),
    ('BH', 'BHR', 'Bahrain'),
    ('BI', 'BDI', 'Burundi'),
    ('BJ', 'BEN', 'Benin'),
    ('BL', 'BLM', 'Saint Barthelemy'),
    ('BM', 'BMU', 'Bermuda'),
    ('BN', 'BRN', 'Brunei'),
    ('BO', 'BOL', 'Bolivia'),
    ('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba'),
    ('BR', 'BRA', 'Brazil'),
    ('BS', 'BHS', 'Bahamas, The'),
    ('BT', 'BTN', 'Bhutan'),
    ('BV', 'BVT', 'Bouvet Island'),
    ('BW', 'BWA', 'Botswana'),
    ('BY', 'BLR', 'Belarus'),
    ('BZ', 'BLZ', 'Belize'),
    ('CA', 'CAN', 'Canada'),
    ('CC', 'CCK', 'Cocos (Keeling) Islands'),
    ('CD', 'COD', 'Democratic Republic of the Congo'),
    ('CF', 'CAF', 'Central African Republic'),
    ('CG', 'COG', 'Congo, Republic of the'),
    ('CH', 'CHE', 'Switzerland'),
    ('CI', 'CIV', 'Cote d''Ivoire'),
    ('CK', 'COK', 'Cook Islands'),
    ('CL', 'CHL', 'Chile'),
    ('CM', 'CMR', 'Cameroon'),
    ('CN', 'CHN', 'China'),
    ('CO', 'COL', 'Colombia'),
    ('CR', 'CRI', 'Costa Rica'),
    ('CU', 'CUB', 'Cuba'),
    ('CV', 'CPV', 'Cape Verde'),
    ('CW', 'CUW', 'Curaçao'),
    ('CX', 'CXR', 'Christmas Island'),
    ('CY', 'CYP', 'Cyprus'),
    ('CZ', 'CZE', 'Czech Republic'),
    ('DE', 'DEU', 'Germany'),
    ('DJ', 'DJI', 'Djibouti'),
    ('DK', 'DNK', 'Denmark'),
    ('DM', 'DMA', 'Dominica'),
    ('DO', 'DOM', 'Dominican Republic'),
    ('DZ', 'DZA', 'Algeria'),
    ('EC', 'ECU', 'Ecuador'),
    ('EE', 'EST', 'Estonia'),
    ('EG', 'EGY', 'Egypt'),
    ('EH', 'ESH', 'Western Sahara'),
    ('ER', 'ERI', 'Eritrea'),
    ('ES', 'ESP', 'Spain'),
    ('ET', 'ETH', 'Ethiopia'),
    ('FI', 'FIN', 'Finland'),
    ('FJ', 'FJI', 'Fiji'),
    ('FK', 'FLK', 'Falkland Islands (Islas Malvinas)'),
    ('FM', 'FSM', 'Micronesia, Federated States of'),
    ('FO', 'FRO', 'Faroe Islands'),
    ('FR', 'FRA', 'France'),
    ('FX', 'FXX', 'France, Metropolitan'),
    ('GA', 'GAB', 'Gabon'),
    ('GB', 'GBR', 'United Kingdom'),
    ('GD', 'GRD', 'Grenada'),
    ('GE', 'GEO', 'Georgia'),
    ('GF', 'GUF', 'French Guiana'),
    ('GG', 'GGY', 'Guernsey'),
    ('GH', 'GHA', 'Ghana'),
    ('GI', 'GIB', 'Gibraltar'),
    ('GL', 'GRL', 'Greenland'),
    ('GM', 'GMB', 'Gambia, The'),
    ('GN', 'GIN', 'Guinea'),
    ('GP', 'GLP', 'Guadeloupe'),
    ('GQ', 'GNQ', 'Equatorial Guinea'),
    ('GR', 'GRC', 'Greece'),
    ('GS', 'SGS', 'South Georgia and the South Sandwich Islands'),
    ('GT', 'GTM', 'Guatemala'),
    ('GU', 'GUM', 'Guam'),
    ('GW', 'GNB', 'Guinea-Bissau'),
    ('GY', 'GUY', 'Guyana'),
    ('HK', 'HKG', 'Hong Kong (China)'),
    ('HM', 'HMD', 'Heard Island and McDonald Islands'),
    ('HN', 'HND', 'Honduras'),
    ('HR', 'HRV', 'Croatia'),
    ('HT', 'HTI', 'Haiti'),
    ('HU', 'HUN', 'Hungary'),
    ('ID', 'IDN', 'Indonesia'),
    ('IE', 'IRL', 'Ireland'),
    ('IL', 'ISR', 'Israel'),
    ('IM', 'IMN', 'Isle of Man'),
    ('IN', 'IND', 'India'),
    ('IO', 'IOT', 'British Indian Ocean Territory'),
    ('IQ', 'IRQ', 'Iraq'),
    ('IR', 'IRN', 'Iran'),
    ('IS', 'ISL', 'Iceland'),
    ('IT', 'ITA', 'Italy'),
    ('JE', 'JEY', 'Jersey'),
    ('JM', 'JAM', 'Jamaica'),
    ('JO', 'JOR', 'Jordan'),
    ('JP', 'JPN', 'Japan'),
    ('KE', 'KEN', 'Kenya'),
    ('KG', 'KGZ', 'Kyrgyzstan'),
    ('KH', 'KHM', 'Cambodia'),
    ('KI', 'KIR', 'Kiribati'),
    ('KM', 'COM', 'Comoros'),
    ('KN', 'KNA', 'Saint Kitts and Nevis'),
    ('KP', 'PRK', 'Korea, North'),
    ('KR', 'KOR', 'Korea, South'),
    ('KW', 'KWT', 'Kuwait'),
    ('KY', 'CYM', 'Cayman Islands'),
    ('KZ', 'KAZ', 'Kazakhstan'),
    ('LA', 'LAO', 'Laos'),
    ('LB', 'LBN', 'Lebanon'),
    ('LC', 'LCA', 'Saint Lucia'),
    ('LI', 'LIE', 'Liechtenstein'),
    ('LK', 'LKA', 'Sri Lanka'),
    ('LR', 'LBR', 'Liberia'),
    ('LS', 'LSO', 'Lesotho'),
    ('LT', 'LTU', 'Lithuania'),
    ('LU', 'LUX', 'Luxembourg'),
    ('LV', 'LVA', 'Latvia'),
    ('LY', 'LBY', 'Libya'),
    ('MA', 'MAR', 'Morocco'),
    ('MC', 'MCO', 'Monaco'),
    ('MD', 'MDA', 'Moldova'),
    ('ME', 'MNE', 'Montenegro'),
    ('MF', 'MAF', 'Saint Martin'),
    ('MG', 'MDG', 'Madagascar'),
    ('MH', 'MHL', 'Marshall Islands'),
    ('MK', 'MKD', 'Macedonia'),
    ('ML', 'MLI', 'Mali'),
    ('MM', 'MMR', 'Myanmar (Burma)'),
    ('MN', 'MNG', 'Mongolia'),
    ('MO', 'MAC', 'Macau (China)'),
    ('MP', 'MNP', 'Northern Mariana Islands'),
    ('MQ', 'MTQ', 'Martinique'),
    ('MR', 'MRT', 'Mauritania'),
    ('MS', 'MSR', 'Montserrat'),
    ('MT', 'MLT', 'Malta'),
    ('MU', 'MUS', 'Mauritius'),
    ('MV', 'MDV', 'Maldives'),
    ('MW', 'MWI', 'Malawi'),
    ('MX', 'MEX', 'Mexico'),
    ('MY', 'MYS', 'Malaysia'),
    ('MZ', 'MOZ', 'Mozambique'),
    ('NA', 'NAM', 'Namibia'),
    ('NC', 'NCL', 'New Caledonia'),
    ('NE', 'NER', 'Niger'),
    ('NF', 'NFK', 'Norfolk Island'),
    ('NG', 'NGA', 'Nigeria'),
    ('NI', 'NIC', 'Nicaragua'),
    ('NL', 'NLD', 'Netherlands'),
    ('NO', 'NOR', 'Norway'),
    ('NP', 'NPL', 'Nepal'),
    ('NR', 'NRU', 'Nauru'),
    ('NU', 'NIU', 'Niue'),
    ('NZ', 'NZL', 'New Zealand'),
    ('OM', 'OMN', 'Oman'),
    ('PA', 'PAN', 'Panama'),
    ('PE', 'PER', 'Peru'),
    ('PF', 'PYF', 'French Polynesia'),
    ('PG', 'PNG', 'Papua New Guinea'),
    ('PH', 'PHL', 'Philippines'),
    ('PK', 'PAK', 'Pakistan'),
    ('PL', 'POL', 'Poland'),
    ('PM', 'SPM', 'Saint Pierre and Miquelon'),
    ('PN', 'PCN', 'Pitcairn Islands'),
    ('PR', 'PRI', 'Puerto Rico'),
    ('PS', 'PSE', 'Occupied Palestinian territories'),
    ('PT', 'PRT', 'Portugal'),
    ('PW', 'PLW', 'Palau'),
    ('PY', 'PRY', 'Paraguay'),
    ('QA', 'QAT', 'Qatar'),
    ('RE', 'REU', 'Reunion'),
    ('RO', 'ROM', 'Romania'),
    ('RS', 'SRB', 'Serbia'),
    ('RU', 'RUS', 'Russia'),
    ('RW', 'RWA', 'Rwanda'),
    ('SA', 'SAU', 'Saudi Arabia'),
    ('SB', 'SLB', 'Solomon Islands'),
    ('SC', 'SYC', 'Seychelles'),
    ('SD', 'SDN', 'Sudan'),
    ('SE', 'SWE', 'Sweden'),
    ('SG', 'SGP', 'Singapore'),
    ('SH', 'SHN', 'Saint Helena'),
    ('SI', 'SVN', 'Slovenia'),
    ('SJ', 'SJM', 'Svalbard'),
    ('SK', 'SVK', 'Slovakia'),
    ('SL', 'SLE', 'Sierra Leone'),
    ('SM', 'SMR', 'San Marino'),
    ('SN', 'SEN', 'Senegal'),
    ('SO', 'SOM', 'Somalia'),
    ('SR', 'SUR', 'Suriname'),
    ('SS', 'SSD', 'South Sudan'),
    ('ST', 'STP', 'Sao Tome and Principe'),
    ('SV', 'SLV', 'El Salvador'),
    ('SX', 'SXM', 'Sint Maarten'),
    ('SY', 'SYR', 'Syria'),
    ('SZ', 'SWZ', 'Swaziland'),
    ('TC', 'TCA', 'Turks and Caicos Islands'),
    ('TD', 'TCD', 'Chad'),
    ('TF', 'ATF', 'French Southern and Antarctic Lands'),
    ('TG', 'TGO', 'Togo'),
    ('TH', 'THA', 'Thailand'),
    ('TJ', 'TJK', 'Tajikistan'),
    ('TK', 'TKL', 'Tokelau'),
    ('TL', 'TLS', 'Democratic Republic of Timor-Leste'),
    ('TM', 'TKM', 'Turkmenistan'),
    ('TN', 'TUN', 'Tunisia'),
    ('TO', 'TON', 'Tonga'),
    ('TP', 'TMP', 'East Timor'),
    ('TR', 'TUR', 'Turkey'),
    ('TT', 'TTO', 'Trinidad and Tobago'),
    ('TV', 'TUV', 'Tuvalu'),
    ('TW', 'TWN', 'Taiwan'),
    ('TZ', 'TZA', 'Tanzania'),
    ('UA', 'UKR', 'Ukraine'),
    ('UG', 'UGA', 'Uganda'),
    ('UM', 'UMI', 'United States Minor Outlying Islands'),
    ('US', 'USA', 'United States'),
    ('UY', 'URY', 'Uruguay'),
    ('UZ', 'UZB', 'Uzbekistan'),
    ('VA', 'VAT', 'Holy See (Vatican City)'),
    ('VC', 'VCT', 'Saint Vincent and the Grenadines'),
    ('VE', 'VEN', 'Venezuela'),
    ('VG', 'VGB', 'British Virgin Islands'),
    ('VI', 'VIR', 'Virgin Islands'),
    ('VN', 'VNM', 'Vietnam'),
    ('VU', 'VUT', 'Vanuatu'),
    ('WF', 'WLF', 'Wallis and Futuna'),
    ('WS', 'WSM', 'Western Samoa'),
    ('XK', 'XKX', 'Kosovo'),
    ('YE', 'YEM', 'Yemen'),
    ('YT', 'MYT', 'Mayotte'),
    ('YU', 'YUG', 'Yugoslavia'),
    ('ZA', 'ZAF', 'South Africa'),
    ('ZM', 'ZWB', 'Zambia'),
    ('ZR', 'ZAR', 'Zaire (Dem Rep of Congo)'),
    ('ZW', 'ZWE', 'Zimbabwe');
