#!/usr/bin/env php
<?php
/*
|--------------------------------------------------------------------------
| Noah v0.2.1
|--------------------------------------------------------------------------
*/

require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;

use TripBuilder\Noah\Db\Install as DatabaseInstall;
use TripBuilder\Noah\Db\Clear as DatabaseClear;

$application = new Application();

$application->add(new DatabaseInstall());
$application->add(new DatabaseClear());

try {
    $application->run();
} catch (Exception $e) {
    // Do nothing
}
