#!/usr/bin/env php
<?php

declare(strict_types=1);
/*
|--------------------------------------------------------------------------
| Noah Commander
|--------------------------------------------------------------------------
*/

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use TripBuilder\Noah\Db\Clear as DatabaseClear;
use TripBuilder\Noah\Db\Install as DatabaseInstall;
use TripBuilder\Noah\Db\Migrate as DatabaseMigrate;
use TripBuilder\Noah\Flights\Cabins as CabinsFlights;
use TripBuilder\Noah\Flights\Cleaning as CleaningFlights;
use TripBuilder\Noah\Flights\Generate as GenerateFlights;
use TripBuilder\Noah\Flights\Realign as RealignFlights;
use TripBuilder\Noah\Flights\Reprice as RepriceFlights;
use TripBuilder\Noah\Grab\Suppliers as GrabSuppliers;

try {
    /*
    |--------------------------------------------------------------------------
    | Application instance
    |--------------------------------------------------------------------------
    */

    $application = new Application();

    /*
    |--------------------------------------------------------------------------
    | Install Database
    |--------------------------------------------------------------------------
    |
    | Adding tables from config files in `config/noah/db/tables` to a database
    | and seeding tables with data from config files in `config/noah/db/seeders`
    |
    */

    $application->add(new DatabaseInstall());

    /*
    |--------------------------------------------------------------------------
    | Clear DB
    |--------------------------------------------------------------------------
    |
    | Purge all data from existing tables in database.
    |
    */

    $application->add(new DatabaseClear());

    /*
    |--------------------------------------------------------------------------
    | Migrate DB
    |--------------------------------------------------------------------------
    |
    | Apply the schema changes app:install cannot make -- a changed type, a
    | dropped column, a new constraint -- and record which have run.
    |
    */

    $application->add(new DatabaseMigrate());

    /*
    |--------------------------------------------------------------------------
    | Generate flights
    |--------------------------------------------------------------------------
    |
    | Generating flights data using existing airports and airlines data,
    | calculating duration between airports, flight time, arrival date and
    | time, base price, taxes and rating. All generated data writing to
    | `flights` table in a database.
    |
    */

    $application->add(new GenerateFlights());

    /*
    |--------------------------------------------------------------------------
    | Cleaning flights
    |--------------------------------------------------------------------------
    |
    | Deleting old flights data from `flights` table in a database.
    | All flights older than the current date will be deleted.
    |
    */

    $application->add(new CleaningFlights());

    /*
    |--------------------------------------------------------------------------
    | Reprice Flights
    |--------------------------------------------------------------------------
    |
    | Recalculating fares on flights already in the network with the current
    | formula in `FarePricing`, in place so bookings keep their flight ids.
    |
    */

    $application->add(new RepriceFlights());

    /*
    |--------------------------------------------------------------------------
    | Cabins on Flights
    |--------------------------------------------------------------------------
    |
    | Adding the `cabins` column and filling in which cabins each flight sells,
    | by the rule in `CabinAvailability`. In place for the same reason as the
    | repricing above -- bookings reference flights by id.
    |
    */

    $application->add(new CabinsFlights());

    /*
    |--------------------------------------------------------------------------
    | Realign Flights
    |--------------------------------------------------------------------------
    |
    | Reassigning the aircraft on flights already in the network with the
    | current rule in `LegBuilder`, and dropping legs longer than anything can
    | fly. Duration, arrival time and cabins all follow from the type.
    |
    */

    $application->add(new RealignFlights());

    // FIXME: for image grabbing
    // $application->add(new GrabSuppliers());

    /*
    |--------------------------------------------------------------------------
    | Run application
    |--------------------------------------------------------------------------
    */

    $application->run();
} catch (Throwable $e) {
    fwrite(STDERR, sprintf('Noah failed: %s: %s%s', $e::class, $e->getMessage(), PHP_EOL));
    exit(1);
}
