<?php

declare(strict_types=1);

namespace TripBuilder\Tests\Unit;

use PHPUnit\Framework\TestCase;
use TripBuilder\Admin;
use TripBuilder\EnvKey;

/**
 * The whole of the authentication, which is small on purpose.
 *
 * One password, one session flag, no accounts table (A3.2, #100). Everything
 * below is a way the panel could end up open to somebody who does not have the
 * password, which is the only failure worth writing tests for here.
 *
 * The hash is a real one for a known password, generated by `password_hash()`
 * and committed, so these run without a `.env` and without hashing on every
 * case.
 */
final class AdminTest extends TestCase
{
    private const string PASSWORD = 'the-one-password';

    /** `password_hash('the-one-password', PASSWORD_DEFAULT)`. */
    private const string HASH = '$2y$12$DzVvlthFVm1dUsY4yS.0luLZYYYnm8BWe.il00TaHdCJ.kKow.8Ea';

    private string|false $before;

    protected function setUp(): void
    {
        $this->before = getenv(EnvKey::AdminPasswordHash->value);
        $_SESSION = [];
        self::setHash(self::HASH);
    }

    protected function tearDown(): void
    {
        putenv($this->before === false
            ? EnvKey::AdminPasswordHash->value
            : EnvKey::AdminPasswordHash->value . '=' . $this->before);
        unset($_ENV[EnvKey::AdminPasswordHash->value]);
        $_SESSION = [];
    }

    public function testTheRightPasswordIsAccepted(): void
    {
        self::assertTrue(Admin::verify(self::PASSWORD));
    }

    public function testTheWrongPasswordIsNot(): void
    {
        self::assertFalse(Admin::verify('the-wrong-password'));
        self::assertFalse(Admin::verify(strtoupper(self::PASSWORD)));
        self::assertFalse(Admin::verify(self::PASSWORD . ' '));
    }

    /**
     * An empty password is not a password, whatever the hash says.
     */
    public function testAnEmptyPasswordIsRefused(): void
    {
        self::assertFalse(Admin::verify(''));
    }

    /**
     * A server nobody has put a password on lets nobody in.
     *
     * The failure this stands against is a panel reachable on a fresh deploy,
     * which is how one ends up open on the internet. Refusing everything is
     * the only safe reading of "no hash".
     */
    public function testNoHashMeansNobodySignsIn(): void
    {
        self::setHash('');

        self::assertFalse(Admin::isConfigured());
        self::assertFalse(Admin::verify(self::PASSWORD));
        self::assertFalse(Admin::verify(''));
    }

    /**
     * And the hash itself is not a password.
     *
     * Worth pinning because it is the shape of a real mistake: somebody pastes
     * the `.env` line into the form.
     */
    public function testTheHashIsNotAPassword(): void
    {
        self::assertFalse(Admin::verify(self::HASH));
    }

    public function testNobodyIsSignedInByDefault(): void
    {
        self::assertFalse(Admin::isSignedIn());
    }

    public function testSigningInAndOut(): void
    {
        Admin::signIn();
        self::assertTrue(Admin::isSignedIn());

        Admin::signOut();
        self::assertFalse(Admin::isSignedIn());
    }

    /**
     * A session left alone stops counting.
     *
     * An admin session is the one on this site worth stealing, and a laptop
     * left open is how it would be.
     */
    public function testAnIdleSessionExpires(): void
    {
        Admin::signIn();

        $_SESSION['admin_seen'] = time() - (Admin::IDLE_MINUTES * 60) - 1;

        self::assertFalse(Admin::isSignedIn());
    }

    /**
     * And working keeps it alive: every admin page asks, so the clock is
     * measuring idleness rather than the length of the visit.
     */
    public function testWorkingKeepsItAlive(): void
    {
        Admin::signIn();

        $_SESSION['admin_seen'] = time() - (Admin::IDLE_MINUTES * 60) + 10;

        self::assertTrue(Admin::isSignedIn());
        self::assertSame(time(), $_SESSION['admin_seen']);
    }

    /**
     * An expired session is cleared, not merely reported.
     *
     * Left in place it would be re-checked on every request, and any later
     * change to the rule would hand it back.
     */
    public function testAnExpiredSessionIsForgotten(): void
    {
        Admin::signIn();
        $_SESSION['admin_seen'] = time() - (Admin::IDLE_MINUTES * 60) - 1;

        Admin::isSignedIn();

        self::assertArrayNotHasKey('admin_since', $_SESSION);
        self::assertArrayNotHasKey('admin_seen', $_SESSION);
    }

    /**
     * A hand-written session value is not a sign-in.
     *
     * `$_SESSION` is server-side, so this is not an attack from outside; it is
     * the guard against another part of the app writing a truthy value under a
     * key this one reads.
     */
    public function testAFlagThatIsNotATimeIsNotASignIn(): void
    {
        $_SESSION['admin_since'] = 'yes';
        $_SESSION['admin_seen'] = 'yes';

        self::assertFalse(Admin::isSignedIn());
    }

    /**
     * Signing out keeps what belongs to the browser rather than to the
     * operator: the CSRF token and the saved flights are the session's, not
     * the sign-in's.
     */
    public function testSigningOutKeepsTheRestOfTheSession(): void
    {
        $_SESSION['csrf_token'] = 'a-token';
        Admin::signIn();
        Admin::signOut();

        self::assertSame('a-token', $_SESSION['csrf_token']);
    }

    private static function setHash(string $hash): void
    {
        putenv(EnvKey::AdminPasswordHash->value . '=' . $hash);
        $_ENV[EnvKey::AdminPasswordHash->value] = $hash;
    }
}
